In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [89]:
df =pd.read_csv(r"C:\Users\mehul\OneDrive\Desktop\Data Analyst\AirBNB\Australia\listings.csv")

In [91]:
df.head()

,id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,review_scores_communication,review_scores_location,review_scores_value,license,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
0,1051911.0,https://www.airbnb.com/rooms/1051911,2.030000e+13,3/3/2025,city scrape,Tree Topz by Beach Stays,Treetopz is a secluded haven perched high abov...,Pittwater on the Northern Beaches of Sydney is...,https://a0.muscache.com/pictures/miso/Hosting-...,24721535,...,4.71,4.71,4.52,PID-STRA-21277,f,73,73,0,0,0.17
1,1100380.0,https://www.airbnb.com/rooms/1100380,2.030000e+13,3/3/2025,city scrape,"Fabulous location, fabulous place",Fresh and fun Hollywood Regency apartment in t...,The cafes and bars are fantastic. Also some br...,https://a0.muscache.com/pictures/048fc478-6378...,6044810,...,4.92,4.97,4.76,PID-STRA-67379,f,1,1,0,0,0.35
2,1125557.0,https://www.airbnb.com/rooms/1125557,2.030000e+13,3/3/2025,city scrape,LUXURY BEACHFRONT APARTMENT,"My warm, comfortable two bedroom apartment lie...",I love being so close to nature. Sometimes I s...,https://a0.muscache.com/pictures/77657551/2b77...,8402583,...,4.89,4.86,4.60,PID-STRA-22786,f,1,0,1,0,0.37
3,1130919.0,https://www.airbnb.com/rooms/1130919,2.030000e+13,3/3/2025,city scrape,Coogee Beach House,Coogee Beach House is contemporary residence i...,In this house you are between Clovelly and Coo...,https://a0.muscache.com/pictures/d7d9da32-d820...,4813247,...,5.00,5.00,4.77,PID-STRA-5749,f,1,1,0,0,0.15
4,11156.0,https://www.airbnb.com/rooms/11156,2.030000e+13,3/3/2025,city scrape,An Oasis in the City,Very central to the city which can be reached ...,"It is very close to everything and everywhere,...",https://a0.muscache.com/pictures/2797669/17895...,40855,...,4.76,4.82,4.71,NaN,f,1,0,1,0,1.04

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18017 entries, 0 to 18016
Data columns (total 79 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            18017 non-null  float64
 1   listing_url                                   18017 non-null  object
 2   scrape_id                                     18017 non-null  float64
 3   last_scraped                                  18017 non-null  object
 4   source                                        18017 non-null  object
 5   name                                          18017 non-null  object
 6   description                                   17703 non-null  object
 7   neighborhood_overview                         8410 non-null   object
 8   picture_url                                   18017 non-null  object
 9   host_id                                       18017 non-null  int64
 10  host_url                                      18017 non-null  object
 11  host_name                                     18009 non-null  object
 12  host_since                                    18009 non-null  object
 13  host_location                                 13300 non-null  object
 14  host_about                                    10480 non-null  object
 15  host_response_time                            15018 non-null  object
 16  host_response_rate                            15018 non-null  object
 17  host_acceptance_rate                          15812 non-null  object
 18  host_is_superhost                             17295 non-null  object
 19  host_thumbnail_url                            18009 non-null  object
 20  host_picture_url                              18009 non-null  object
 21  host_neighbourhood                            4914 non-null   object
 22  host_listings_count                           18017 non-null  int64
 23  host_total_listings_count                     18017 non-null  int64
 24  host_verifications                            18009 non-null  object
 25  host_has_profile_pic                          18009 non-null  object
 26  host_identity_verified                        18009 non-null  object
 27  neighbourhood                                 8410 non-null   object
 28  neighbourhood_cleansed                        18017 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      18017 non-null  float64
 31  longitude                                     18017 non-null  float64
 32  property_type                                 18017 non-null  object
 33  room_type                                     18017 non-null  object
 34  accommodates                                  18017 non-null  int64
 35  bathrooms                                     18017 non-null  float64
 36  bathrooms_text                                18006 non-null  object
 37  bedrooms                                      18017 non-null  int64
 38  beds                                          18017 non-null  int64
 39  amenities                                     18017 non-null  object
 40  price                                         18017 non-null  object
 41  minimum_nights                                18017 non-null  int64
 42  maximum_nights                                18017 non-null  int64
 43  minimum_minimum_nights                        18017 non-null  int64
 44  maximum_minimum_nights                        18017 non-null  int64
 45  minimum_maximum_nights                        18017 non-null  int64
 46  maximum_maximum_nights                        18017 non-null  int64
 47  minimum_nights_avg_ntm                        18017 non-null  float64
 48  maximum_nights_avg_ntm                        18017 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              17869 non-null  object
 51  availability_30                               18017 non-null  int64
 52  availability_60                               18017 non-null  int64
 53  availability_90                               18017 non-null  int64
 54  availability_365                              18017 non-null  int64
 55  calendar_last_scraped                         18017 non-null  object
 56  number_of_reviews                             18017 non-null  int64
 57  number_of_reviews_ltm                         18017 non-null  int64
 58  number_of_reviews_l30d                        18017 non-null  int64
 59  availability_eoy                              18017 non-null  int64
 60  number_of_reviews_ly                          18017 non-null  int64
 61  estimated_occupancy_l365d                     18017 non-null  int64
 62  estimated_revenue_l365d                       18017 non-null  int64
 63  first_review                                  14983 non-null  object
 64  last_review                                   14983 non-null  object
 65  review_scores_rating                          18017 non-null  float64
 66  review_scores_accuracy                        18017 non-null  float64
 67  review_scores_cleanliness                     18017 non-null  float64
 68  review_scores_checkin                         18017 non-null  float64
 69  review_scores_communication                   18017 non-null  float64
 70  review_scores_location                        18017 non-null  float64
 71  review_scores_value                           18017 non-null  float64
 72  license                                       16593 non-null  object
 73  instant_bookable                              18017 non-null  object
 74  calculated_host_listings_count                18017 non-null  int64
 75  calculated_host_listings_count_entire_homes   18017 non-null  int64
 76  calculated_host_listings_count_private_rooms  18017 non-null  int64
 77  calculated_host_listings_count_shared_rooms   18017 non-null  int64
 78  reviews_per_month                             18017 non-null  float64
dtypes: float64(17), int64(27), object(35)
memory usage: 10.9+ MB

In [11]:
df.describe()

,id,scrape_id,host_id,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,latitude,longitude,accommodates,bathrooms,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month
count,1.801700e+04,1.801700e+04,1.801700e+04,18017.000000,18017.000000,0.0,18017.000000,18017.000000,18017.000000,18017.000000,...,18017.000000,18017.00000,18017.000000,18017.000000,18017.000000,18017.000000,18017.000000,18017.000000,18017.000000,18017.000000
mean,7.119737e+17,2.030000e+13,2.027744e+08,30.720708,45.609702,NaN,-33.850777,151.176460,4.061997,1.281429,...,3.871312,3.99526,4.010984,4.001214,3.834963,19.447466,15.461231,3.951435,0.007937,1.242223
std,5.337916e+17,0.000000e+00,2.019040e+08,97.022536,122.516210,NaN,0.089524,0.114566,2.516219,0.902965,...,1.799076,1.83252,1.839578,1.826431,1.779245,40.017646,32.971554,23.650871,0.147105,1.446823
min,1.115600e+04,2.030000e+13,3.558200e+04,0.000000,0.000000,NaN,-34.132390,150.630490,1.000000,0.000000,...,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,4.223758e+07,2.030000e+13,2.719164e+07,1.000000,1.000000,NaN,-33.896820,151.135980,2.000000,1.000000,...,4.160000,4.50000,4.540000,4.530000,4.140000,1.000000,1.000000,0.000000,0.000000,0.140000
50%,9.010000e+17,2.030000e+13,1.231830e+08,3.000000,4.000000,NaN,-33.874972,151.205450,4.000000,1.000000,...,4.710000,4.88000,4.910000,4.860000,4.660000,2.000000,1.000000,0.000000,0.000000,0.800000
75%,1.190000e+18,2.030000e+13,3.426539e+08,23.000000,33.000000,NaN,-33.801870,151.253860,6.000000,2.000000,...,4.930000,5.00000,5.000000,5.000000,4.850000,18.000000,12.000000,1.000000,0.000000,1.860000
max,1.370000e+18,2.030000e+13,6.818117e+08,863.000000,944.000000,NaN,-33.383640,151.340140,16.000000,21.000000,...,5.000000,5.00000,5.000000,5.000000,5.000000,221.000000,189.000000,211.000000,5.000000,17.960000

In [13]:
df.columns

Index(['id', 'listing_url', 'scrape_id', 'last_scraped', 'source', 'name',
       'description', 'neighborhood_overview', 'picture_url', 'host_id',
       'host_url', 'host_name', 'host_since', 'host_location', 'host_about',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_thumbnail_url', 'host_picture_url',
       'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [17]:
df.isnull().sum()
(df.isnull().sum()/len(df))*100

id                                              0.0
listing_url                                     0.0
scrape_id                                       0.0
last_scraped                                    0.0
source                                          0.0
                                               ...
calculated_host_listings_count                  0.0
calculated_host_listings_count_entire_homes     0.0
calculated_host_listings_count_private_rooms    0.0
calculated_host_listings_count_shared_rooms     0.0
reviews_per_month                               0.0
Length: 79, dtype: float64

In [33]:
#Check Duplicate Columns
df.duplicated().sum()

2

In [29]:
#Drop the Columns
df = df.drop(columns=[
    'scrape_id',
    'last_scraped',
    'listing_url',
    'picture_url',
    'host_url'
], errors='ignore')

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18017 entries, 0 to 18016
Data columns (total 74 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            18017 non-null  float64
 1   source                                        18017 non-null  object
 2   name                                          18017 non-null  object
 3   description                                   17703 non-null  object
 4   neighborhood_overview                         8410 non-null   object
 5   host_id                                       18017 non-null  int64
 6   host_name                                     18009 non-null  object
 7   host_since                                    18009 non-null  object
 8   host_location                                 13300 non-null  object
 9   host_about                                    10480 non-null  object
 10  host_response_time                            15018 non-null  object
 11  host_response_rate                            15018 non-null  object
 12  host_acceptance_rate                          15812 non-null  object
 13  host_is_superhost                             17295 non-null  object
 14  host_thumbnail_url                            18009 non-null  object
 15  host_picture_url                              18009 non-null  object
 16  host_neighbourhood                            4914 non-null   object
 17  host_listings_count                           18017 non-null  int64
 18  host_total_listings_count                     18017 non-null  int64
 19  host_verifications                            18009 non-null  object
 20  host_has_profile_pic                          18009 non-null  object
 21  host_identity_verified                        18009 non-null  object
 22  neighbourhood                                 8410 non-null   object
 23  neighbourhood_cleansed                        18017 non-null  object
 24  neighbourhood_group_cleansed                  0 non-null      float64
 25  latitude                                      18017 non-null  float64
 26  longitude                                     18017 non-null  float64
 27  property_type                                 18017 non-null  object
 28  room_type                                     18017 non-null  object
 29  accommodates                                  18017 non-null  int64
 30  bathrooms                                     18017 non-null  float64
 31  bathrooms_text                                18006 non-null  object
 32  bedrooms                                      18017 non-null  int64
 33  beds                                          18017 non-null  int64
 34  amenities                                     18017 non-null  object
 35  price                                         18017 non-null  object
 36  minimum_nights                                18017 non-null  int64
 37  maximum_nights                                18017 non-null  int64
 38  minimum_minimum_nights                        18017 non-null  int64
 39  maximum_minimum_nights                        18017 non-null  int64
 40  minimum_maximum_nights                        18017 non-null  int64
 41  maximum_maximum_nights                        18017 non-null  int64
 42  minimum_nights_avg_ntm                        18017 non-null  float64
 43  maximum_nights_avg_ntm                        18017 non-null  float64
 44  calendar_updated                              0 non-null      float64
 45  has_availability                              17869 non-null  object
 46  availability_30                               18017 non-null  int64
 47  availability_60                               18017 non-null  int64
 48  availability_90                               18017 non-null  int64
 49  availability_365                              18017 non-null  int64
 50  calendar_last_scraped                         18017 non-null  object
 51  number_of_reviews                             18017 non-null  int64
 52  number_of_reviews_ltm                         18017 non-null  int64
 53  number_of_reviews_l30d                        18017 non-null  int64
 54  availability_eoy                              18017 non-null  int64
 55  number_of_reviews_ly                          18017 non-null  int64
 56  estimated_occupancy_l365d                     18017 non-null  int64
 57  estimated_revenue_l365d                       18017 non-null  int64
 58  first_review                                  14983 non-null  object
 59  last_review                                   14983 non-null  object
 60  review_scores_rating                          18017 non-null  float64
 61  review_scores_accuracy                        18017 non-null  float64
 62  review_scores_cleanliness                     18017 non-null  float64
 63  review_scores_checkin                         18017 non-null  float64
 64  review_scores_communication                   18017 non-null  float64
 65  review_scores_location                        18017 non-null  float64
 66  review_scores_value                           18017 non-null  float64
 67  license                                       16593 non-null  object
 68  instant_bookable                              18017 non-null  object
 69  calculated_host_listings_count                18017 non-null  int64
 70  calculated_host_listings_count_entire_homes   18017 non-null  int64
 71  calculated_host_listings_count_private_rooms  18017 non-null  int64
 72  calculated_host_listings_count_shared_rooms   18017 non-null  int64
 73  reviews_per_month                             18017 non-null  float64
dtypes: float64(16), int64(27), object(31)
memory usage: 10.2+ MB

In [35]:
#Clean the Price Column
df['price'] =df['price'].replace('[/$,]', '', regex=True)
df['price'] = df['price'].astype(float)
df['price'].head()

0    657.0
1    210.0
2    157.0
3    950.0
4     65.0
Name: price, dtype: float64

In [37]:
#Convert Data Type
df['host_since'] =pd.to_datetime(df['host_since'])
df['last_review'] =pd.to_datetime(df['last_review'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18017 entries, 0 to 18016
Data columns (total 74 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            18017 non-null  float64
 1   source                                        18017 non-null  object
 2   name                                          18017 non-null  object
 3   description                                   17703 non-null  object
 4   neighborhood_overview                         8410 non-null   object
 5   host_id                                       18017 non-null  int64
 6   host_name                                     18009 non-null  object
 7   host_since                                    18009 non-null  datetime64[ns]
 8   host_location                                 13300 non-null  object
 9   host_about                                    10480 non-null  object
 10  host_response_time                            15018 non-null  object
 11  host_response_rate                            15018 non-null  object
 12  host_acceptance_rate                          15812 non-null  object
 13  host_is_superhost                             17295 non-null  object
 14  host_thumbnail_url                            18009 non-null  object
 15  host_picture_url                              18009 non-null  object
 16  host_neighbourhood                            4914 non-null   object
 17  host_listings_count                           18017 non-null  int64
 18  host_total_listings_count                     18017 non-null  int64
 19  host_verifications                            18009 non-null  object
 20  host_has_profile_pic                          18009 non-null  object
 21  host_identity_verified                        18009 non-null  object
 22  neighbourhood                                 8410 non-null   object
 23  neighbourhood_cleansed                        18017 non-null  object
 24  neighbourhood_group_cleansed                  0 non-null      float64
 25  latitude                                      18017 non-null  float64
 26  longitude                                     18017 non-null  float64
 27  property_type                                 18017 non-null  object
 28  room_type                                     18017 non-null  object
 29  accommodates                                  18017 non-null  int64
 30  bathrooms                                     18017 non-null  float64
 31  bathrooms_text                                18006 non-null  object
 32  bedrooms                                      18017 non-null  int64
 33  beds                                          18017 non-null  int64
 34  amenities                                     18017 non-null  object
 35  price                                         18017 non-null  float64
 36  minimum_nights                                18017 non-null  int64
 37  maximum_nights                                18017 non-null  int64
 38  minimum_minimum_nights                        18017 non-null  int64
 39  maximum_minimum_nights                        18017 non-null  int64
 40  minimum_maximum_nights                        18017 non-null  int64
 41  maximum_maximum_nights                        18017 non-null  int64
 42  minimum_nights_avg_ntm                        18017 non-null  float64
 43  maximum_nights_avg_ntm                        18017 non-null  float64
 44  calendar_updated                              0 non-null      float64
 45  has_availability                              17869 non-null  object
 46  availability_30                               18017 non-null  int64
 47  availability_60                               18017 non-null  int64
 48  availability_90                               18017 non-null  int64
 49  availability_365                              18017 non-null  int64
 50  calendar_last_scraped                         18017 non-null  object
 51  number_of_reviews                             18017 non-null  int64
 52  number_of_reviews_ltm                         18017 non-null  int64
 53  number_of_reviews_l30d                        18017 non-null  int64
 54  availability_eoy                              18017 non-null  int64
 55  number_of_reviews_ly                          18017 non-null  int64
 56  estimated_occupancy_l365d                     18017 non-null  int64
 57  estimated_revenue_l365d                       18017 non-null  int64
 58  first_review                                  14983 non-null  object
 59  last_review                                   14983 non-null  datetime64[ns]
 60  review_scores_rating                          18017 non-null  float64
 61  review_scores_accuracy                        18017 non-null  float64
 62  review_scores_cleanliness                     18017 non-null  float64
 63  review_scores_checkin                         18017 non-null  float64
 64  review_scores_communication                   18017 non-null  float64
 65  review_scores_location                        18017 non-null  float64
 66  review_scores_value                           18017 non-null  float64
 67  license                                       16593 non-null  object
 68  instant_bookable                              18017 non-null  object
 69  calculated_host_listings_count                18017 non-null  int64
 70  calculated_host_listings_count_entire_homes   18017 non-null  int64
 71  calculated_host_listings_count_private_rooms  18017 non-null  int64
 72  calculated_host_listings_count_shared_rooms   18017 non-null  int64
 73  reviews_per_month                             18017 non-null  float64
dtypes: datetime64[ns](2), float64(17), int64(27), object(28)
memory usage: 10.2+ MB

In [39]:
#Numeric Columns Stored as Objects
df['bedrooms'] =pd.to_numeric(df['bedrooms'], errors='coerce')
df['beds'] =pd.to_numeric(df['beds'], errors='coerce')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18017 entries, 0 to 18016
Data columns (total 74 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            18017 non-null  float64
 1   source                                        18017 non-null  object
 2   name                                          18017 non-null  object
 3   description                                   17703 non-null  object
 4   neighborhood_overview                         8410 non-null   object
 5   host_id                                       18017 non-null  int64
 6   host_name                                     18009 non-null  object
 7   host_since                                    18009 non-null  datetime64[ns]
 8   host_location                                 13300 non-null  object
 9   host_about                                    10480 non-null  object
 10  host_response_time                            15018 non-null  object
 11  host_response_rate                            15018 non-null  object
 12  host_acceptance_rate                          15812 non-null  object
 13  host_is_superhost                             17295 non-null  object
 14  host_thumbnail_url                            18009 non-null  object
 15  host_picture_url                              18009 non-null  object
 16  host_neighbourhood                            4914 non-null   object
 17  host_listings_count                           18017 non-null  int64
 18  host_total_listings_count                     18017 non-null  int64
 19  host_verifications                            18009 non-null  object
 20  host_has_profile_pic                          18009 non-null  object
 21  host_identity_verified                        18009 non-null  object
 22  neighbourhood                                 8410 non-null   object
 23  neighbourhood_cleansed                        18017 non-null  object
 24  neighbourhood_group_cleansed                  0 non-null      float64
 25  latitude                                      18017 non-null  float64
 26  longitude                                     18017 non-null  float64
 27  property_type                                 18017 non-null  object
 28  room_type                                     18017 non-null  object
 29  accommodates                                  18017 non-null  int64
 30  bathrooms                                     18017 non-null  float64
 31  bathrooms_text                                18006 non-null  object
 32  bedrooms                                      18017 non-null  int64
 33  beds                                          18017 non-null  int64
 34  amenities                                     18017 non-null  object
 35  price                                         18017 non-null  float64
 36  minimum_nights                                18017 non-null  int64
 37  maximum_nights                                18017 non-null  int64
 38  minimum_minimum_nights                        18017 non-null  int64
 39  maximum_minimum_nights                        18017 non-null  int64
 40  minimum_maximum_nights                        18017 non-null  int64
 41  maximum_maximum_nights                        18017 non-null  int64
 42  minimum_nights_avg_ntm                        18017 non-null  float64
 43  maximum_nights_avg_ntm                        18017 non-null  float64
 44  calendar_updated                              0 non-null      float64
 45  has_availability                              17869 non-null  object
 46  availability_30                               18017 non-null  int64
 47  availability_60                               18017 non-null  int64
 48  availability_90                               18017 non-null  int64
 49  availability_365                              18017 non-null  int64
 50  calendar_last_scraped                         18017 non-null  object
 51  number_of_reviews                             18017 non-null  int64
 52  number_of_reviews_ltm                         18017 non-null  int64
 53  number_of_reviews_l30d                        18017 non-null  int64
 54  availability_eoy                              18017 non-null  int64
 55  number_of_reviews_ly                          18017 non-null  int64
 56  estimated_occupancy_l365d                     18017 non-null  int64
 57  estimated_revenue_l365d                       18017 non-null  int64
 58  first_review                                  14983 non-null  object
 59  last_review                                   14983 non-null  datetime64[ns]
 60  review_scores_rating                          18017 non-null  float64
 61  review_scores_accuracy                        18017 non-null  float64
 62  review_scores_cleanliness                     18017 non-null  float64
 63  review_scores_checkin                         18017 non-null  float64
 64  review_scores_communication                   18017 non-null  float64
 65  review_scores_location                        18017 non-null  float64
 66  review_scores_value                           18017 non-null  float64
 67  license                                       16593 non-null  object
 68  instant_bookable                              18017 non-null  object
 69  calculated_host_listings_count                18017 non-null  int64
 70  calculated_host_listings_count_entire_homes   18017 non-null  int64
 71  calculated_host_listings_count_private_rooms  18017 non-null  int64
 72  calculated_host_listings_count_shared_rooms   18017 non-null  int64
 73  reviews_per_month                             18017 non-null  float64
dtypes: datetime64[ns](2), float64(17), int64(27), object(28)
memory usage: 10.2+ MB

In [43]:
#Detect Wrong Type
df.select_dtypes(include='object').head()

,source,name,description,neighborhood_overview,host_name,host_location,host_about,host_response_time,host_response_rate,host_acceptance_rate,...,neighbourhood_cleansed,property_type,room_type,bathrooms_text,amenities,has_availability,calendar_last_scraped,first_review,license,instant_bookable
0,city scrape,Tree Topz by Beach Stays,Treetopz is a secluded haven perched high abov...,Pittwater on the Northern Beaches of Sydney is...,Beach Stays,NaN,Beach Stays has serviced the Northern Beaches ...,within a few hours,89%,91%,...,Pittwater,Entire home,Entire home/apt,2 baths,"[""Dishwasher"", ""Smoke alarm"", ""Fire extinguish...",t,3/3/2025,9/30/2014,PID-STRA-21277,f
1,city scrape,"Fabulous location, fabulous place",Fresh and fun Hollywood Regency apartment in t...,The cafes and bars are fantastic. Also some br...,Trevor,"Surry Hills, Australia",I'm a 30-something gay guy working in the Arts...,within a few hours,100%,89%,...,Sydney,Entire rental unit,Entire home/apt,1 bath,"[""Outdoor furniture"", ""Smoke alarm"", ""Cooking ...",t,3/3/2025,7/24/2016,PID-STRA-67379,f
2,city scrape,LUXURY BEACHFRONT APARTMENT,"My warm, comfortable two bedroom apartment lie...",I love being so close to nature. Sometimes I s...,Janice,"Cronulla, Australia",I live in a beautiful apartment on the beach. ...,within a few hours,100%,100%,...,Sutherland Shire,Private room in rental unit,Private room,1 shared bath,"[""Children\u2019s books and toys"", ""Beach acce...",t,3/3/2025,6/29/2015,PID-STRA-22786,f
3,city scrape,Coogee Beach House,Coogee Beach House is contemporary residence i...,In this house you are between Clovelly and Coo...,Kristin,"New South Wales, Australia",Family of 4. Ian owns a design and brand comm...,within an hour,100%,67%,...,Randwick,Entire home,Entire home/apt,2.5 baths,"[""Outdoor furniture"", ""Dishwasher"", ""Smoke ala...",t,3/3/2025,12/26/2017,PID-STRA-5749,f
4,city scrape,An Oasis in the City,Very central to the city which can be reached ...,"It is very close to everything and everywhere,...",Colleen,"Potts Point, Australia","Recently retired, I've lived & worked on 4 con...",a few days or more,0%,NaN,...,Sydney,Private room in rental unit,Private room,1 shared bath,"[""Dishwasher"", ""Smoke alarm"", ""Fire extinguish...",t,3/3/2025,12/5/2009,NaN,f

In [55]:
#Columns that Should Became Numeric
df['host_response_rate'] = pd.to_numeric(
    df['host_response_rate'].astype(str).str.replace('%',''),
    errors='coerce'
)

df['host_acceptance_rate'] = pd.to_numeric(
    df['host_acceptance_rate'].astype(str).str.replace('%',''),
    errors='coerce'
)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18017 entries, 0 to 18016
Data columns (total 74 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            18017 non-null  float64
 1   source                                        18017 non-null  object
 2   name                                          18017 non-null  object
 3   description                                   17703 non-null  object
 4   neighborhood_overview                         8410 non-null   object
 5   host_id                                       18017 non-null  int64
 6   host_name                                     18009 non-null  object
 7   host_since                                    18009 non-null  datetime64[ns]
 8   host_location                                 13300 non-null  object
 9   host_about                                    10480 non-null  object
 10  host_response_time                            15018 non-null  object
 11  host_response_rate                            15018 non-null  float64
 12  host_acceptance_rate                          15812 non-null  float64
 13  host_is_superhost                             17295 non-null  object
 14  host_thumbnail_url                            18009 non-null  object
 15  host_picture_url                              18009 non-null  object
 16  host_neighbourhood                            4914 non-null   object
 17  host_listings_count                           18017 non-null  int64
 18  host_total_listings_count                     18017 non-null  int64
 19  host_verifications                            18009 non-null  object
 20  host_has_profile_pic                          18009 non-null  object
 21  host_identity_verified                        18009 non-null  object
 22  neighbourhood                                 8410 non-null   object
 23  neighbourhood_cleansed                        18017 non-null  object
 24  neighbourhood_group_cleansed                  0 non-null      float64
 25  latitude                                      18017 non-null  float64
 26  longitude                                     18017 non-null  float64
 27  property_type                                 18017 non-null  object
 28  room_type                                     18017 non-null  object
 29  accommodates                                  18017 non-null  int64
 30  bathrooms                                     18017 non-null  float64
 31  bathrooms_text                                18006 non-null  object
 32  bedrooms                                      18017 non-null  int64
 33  beds                                          18017 non-null  int64
 34  amenities                                     18017 non-null  object
 35  price                                         18017 non-null  float64
 36  minimum_nights                                18017 non-null  int64
 37  maximum_nights                                18017 non-null  int64
 38  minimum_minimum_nights                        18017 non-null  int64
 39  maximum_minimum_nights                        18017 non-null  int64
 40  minimum_maximum_nights                        18017 non-null  int64
 41  maximum_maximum_nights                        18017 non-null  int64
 42  minimum_nights_avg_ntm                        18017 non-null  float64
 43  maximum_nights_avg_ntm                        18017 non-null  float64
 44  calendar_updated                              0 non-null      float64
 45  has_availability                              17869 non-null  object
 46  availability_30                               18017 non-null  int64
 47  availability_60                               18017 non-null  int64
 48  availability_90                               18017 non-null  int64
 49  availability_365                              18017 non-null  int64
 50  calendar_last_scraped                         18017 non-null  object
 51  number_of_reviews                             18017 non-null  int64
 52  number_of_reviews_ltm                         18017 non-null  int64
 53  number_of_reviews_l30d                        18017 non-null  int64
 54  availability_eoy                              18017 non-null  int64
 55  number_of_reviews_ly                          18017 non-null  int64
 56  estimated_occupancy_l365d                     18017 non-null  int64
 57  estimated_revenue_l365d                       18017 non-null  int64
 58  first_review                                  14983 non-null  object
 59  last_review                                   14983 non-null  datetime64[ns]
 60  review_scores_rating                          18017 non-null  float64
 61  review_scores_accuracy                        18017 non-null  float64
 62  review_scores_cleanliness                     18017 non-null  float64
 63  review_scores_checkin                         18017 non-null  float64
 64  review_scores_communication                   18017 non-null  float64
 65  review_scores_location                        18017 non-null  float64
 66  review_scores_value                           18017 non-null  float64
 67  license                                       16593 non-null  object
 68  instant_bookable                              18017 non-null  object
 69  calculated_host_listings_count                18017 non-null  int64
 70  calculated_host_listings_count_entire_homes   18017 non-null  int64
 71  calculated_host_listings_count_private_rooms  18017 non-null  int64
 72  calculated_host_listings_count_shared_rooms   18017 non-null  int64
 73  reviews_per_month                             18017 non-null  float64
dtypes: datetime64[ns](2), float64(19), int64(27), object(26)
memory usage: 10.2+ MB

In [59]:
#Convert Date Columns
df['calendar_last_scraped'] = pd.to_datetime(df['calendar_last_scraped'])
df['first_review'] = pd.to_datetime(df['first_review'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18017 entries, 0 to 18016
Data columns (total 74 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            18017 non-null  float64
 1   source                                        18017 non-null  object
 2   name                                          18017 non-null  object
 3   description                                   17703 non-null  object
 4   neighborhood_overview                         8410 non-null   object
 5   host_id                                       18017 non-null  int64
 6   host_name                                     18009 non-null  object
 7   host_since                                    18009 non-null  datetime64[ns]
 8   host_location                                 13300 non-null  object
 9   host_about                                    10480 non-null  object
 10  host_response_time                            15018 non-null  object
 11  host_response_rate                            15018 non-null  float64
 12  host_acceptance_rate                          15812 non-null  float64
 13  host_is_superhost                             17295 non-null  object
 14  host_thumbnail_url                            18009 non-null  object
 15  host_picture_url                              18009 non-null  object
 16  host_neighbourhood                            4914 non-null   object
 17  host_listings_count                           18017 non-null  int64
 18  host_total_listings_count                     18017 non-null  int64
 19  host_verifications                            18009 non-null  object
 20  host_has_profile_pic                          18009 non-null  object
 21  host_identity_verified                        18009 non-null  object
 22  neighbourhood                                 8410 non-null   object
 23  neighbourhood_cleansed                        18017 non-null  object
 24  neighbourhood_group_cleansed                  0 non-null      float64
 25  latitude                                      18017 non-null  float64
 26  longitude                                     18017 non-null  float64
 27  property_type                                 18017 non-null  object
 28  room_type                                     18017 non-null  object
 29  accommodates                                  18017 non-null  int64
 30  bathrooms                                     18017 non-null  float64
 31  bathrooms_text                                18006 non-null  object
 32  bedrooms                                      18017 non-null  int64
 33  beds                                          18017 non-null  int64
 34  amenities                                     18017 non-null  object
 35  price                                         18017 non-null  float64
 36  minimum_nights                                18017 non-null  int64
 37  maximum_nights                                18017 non-null  int64
 38  minimum_minimum_nights                        18017 non-null  int64
 39  maximum_minimum_nights                        18017 non-null  int64
 40  minimum_maximum_nights                        18017 non-null  int64
 41  maximum_maximum_nights                        18017 non-null  int64
 42  minimum_nights_avg_ntm                        18017 non-null  float64
 43  maximum_nights_avg_ntm                        18017 non-null  float64
 44  calendar_updated                              0 non-null      float64
 45  has_availability                              17869 non-null  object
 46  availability_30                               18017 non-null  int64
 47  availability_60                               18017 non-null  int64
 48  availability_90                               18017 non-null  int64
 49  availability_365                              18017 non-null  int64
 50  calendar_last_scraped                         18017 non-null  datetime64[ns]
 51  number_of_reviews                             18017 non-null  int64
 52  number_of_reviews_ltm                         18017 non-null  int64
 53  number_of_reviews_l30d                        18017 non-null  int64
 54  availability_eoy                              18017 non-null  int64
 55  number_of_reviews_ly                          18017 non-null  int64
 56  estimated_occupancy_l365d                     18017 non-null  int64
 57  estimated_revenue_l365d                       18017 non-null  int64
 58  first_review                                  14983 non-null  datetime64[ns]
 59  last_review                                   14983 non-null  datetime64[ns]
 60  review_scores_rating                          18017 non-null  float64
 61  review_scores_accuracy                        18017 non-null  float64
 62  review_scores_cleanliness                     18017 non-null  float64
 63  review_scores_checkin                         18017 non-null  float64
 64  review_scores_communication                   18017 non-null  float64
 65  review_scores_location                        18017 non-null  float64
 66  review_scores_value                           18017 non-null  float64
 67  license                                       16593 non-null  object
 68  instant_bookable                              18017 non-null  object
 69  calculated_host_listings_count                18017 non-null  int64
 70  calculated_host_listings_count_entire_homes   18017 non-null  int64
 71  calculated_host_listings_count_private_rooms  18017 non-null  int64
 72  calculated_host_listings_count_shared_rooms   18017 non-null  int64
 73  reviews_per_month                             18017 non-null  float64
dtypes: datetime64[ns](4), float64(19), int64(27), object(24)
memory usage: 10.2+ MB

In [61]:
#Convert Boolean Columns
df['instant_bookable'] = df['instant_bookable'].map({'t':True,'f':False})
df['has_availability'] = df['has_availability'].map({'t':True,'f':False})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18017 entries, 0 to 18016
Data columns (total 74 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            18017 non-null  float64
 1   source                                        18017 non-null  object
 2   name                                          18017 non-null  object
 3   description                                   17703 non-null  object
 4   neighborhood_overview                         8410 non-null   object
 5   host_id                                       18017 non-null  int64
 6   host_name                                     18009 non-null  object
 7   host_since                                    18009 non-null  datetime64[ns]
 8   host_location                                 13300 non-null  object
 9   host_about                                    10480 non-null  object
 10  host_response_time                            15018 non-null  object
 11  host_response_rate                            15018 non-null  float64
 12  host_acceptance_rate                          15812 non-null  float64
 13  host_is_superhost                             17295 non-null  object
 14  host_thumbnail_url                            18009 non-null  object
 15  host_picture_url                              18009 non-null  object
 16  host_neighbourhood                            4914 non-null   object
 17  host_listings_count                           18017 non-null  int64
 18  host_total_listings_count                     18017 non-null  int64
 19  host_verifications                            18009 non-null  object
 20  host_has_profile_pic                          18009 non-null  object
 21  host_identity_verified                        18009 non-null  object
 22  neighbourhood                                 8410 non-null   object
 23  neighbourhood_cleansed                        18017 non-null  object
 24  neighbourhood_group_cleansed                  0 non-null      float64
 25  latitude                                      18017 non-null  float64
 26  longitude                                     18017 non-null  float64
 27  property_type                                 18017 non-null  object
 28  room_type                                     18017 non-null  object
 29  accommodates                                  18017 non-null  int64
 30  bathrooms                                     18017 non-null  float64
 31  bathrooms_text                                18006 non-null  object
 32  bedrooms                                      18017 non-null  int64
 33  beds                                          18017 non-null  int64
 34  amenities                                     18017 non-null  object
 35  price                                         18017 non-null  float64
 36  minimum_nights                                18017 non-null  int64
 37  maximum_nights                                18017 non-null  int64
 38  minimum_minimum_nights                        18017 non-null  int64
 39  maximum_minimum_nights                        18017 non-null  int64
 40  minimum_maximum_nights                        18017 non-null  int64
 41  maximum_maximum_nights                        18017 non-null  int64
 42  minimum_nights_avg_ntm                        18017 non-null  float64
 43  maximum_nights_avg_ntm                        18017 non-null  float64
 44  calendar_updated                              0 non-null      float64
 45  has_availability                              17869 non-null  object
 46  availability_30                               18017 non-null  int64
 47  availability_60                               18017 non-null  int64
 48  availability_90                               18017 non-null  int64
 49  availability_365                              18017 non-null  int64
 50  calendar_last_scraped                         18017 non-null  datetime64[ns]
 51  number_of_reviews                             18017 non-null  int64
 52  number_of_reviews_ltm                         18017 non-null  int64
 53  number_of_reviews_l30d                        18017 non-null  int64
 54  availability_eoy                              18017 non-null  int64
 55  number_of_reviews_ly                          18017 non-null  int64
 56  estimated_occupancy_l365d                     18017 non-null  int64
 57  estimated_revenue_l365d                       18017 non-null  int64
 58  first_review                                  14983 non-null  datetime64[ns]
 59  last_review                                   14983 non-null  datetime64[ns]
 60  review_scores_rating                          18017 non-null  float64
 61  review_scores_accuracy                        18017 non-null  float64
 62  review_scores_cleanliness                     18017 non-null  float64
 63  review_scores_checkin                         18017 non-null  float64
 64  review_scores_communication                   18017 non-null  float64
 65  review_scores_location                        18017 non-null  float64
 66  review_scores_value                           18017 non-null  float64
 67  license                                       16593 non-null  object
 68  instant_bookable                              18017 non-null  bool
 69  calculated_host_listings_count                18017 non-null  int64
 70  calculated_host_listings_count_entire_homes   18017 non-null  int64
 71  calculated_host_listings_count_private_rooms  18017 non-null  int64
 72  calculated_host_listings_count_shared_rooms   18017 non-null  int64
 73  reviews_per_month                             18017 non-null  float64
dtypes: bool(1), datetime64[ns](4), float64(19), int64(27), object(23)
memory usage: 10.1+ MB

In [63]:
#Clean Bathroom Column
df['bathrooms'] = df['bathrooms_text'].str.extract('(\d+\.?\d*)').astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18017 entries, 0 to 18016
Data columns (total 74 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            18017 non-null  float64
 1   source                                        18017 non-null  object
 2   name                                          18017 non-null  object
 3   description                                   17703 non-null  object
 4   neighborhood_overview                         8410 non-null   object
 5   host_id                                       18017 non-null  int64
 6   host_name                                     18009 non-null  object
 7   host_since                                    18009 non-null  datetime64[ns]
 8   host_location                                 13300 non-null  object
 9   host_about                                    10480 non-null  object
 10  host_response_time                            15018 non-null  object
 11  host_response_rate                            15018 non-null  float64
 12  host_acceptance_rate                          15812 non-null  float64
 13  host_is_superhost                             17295 non-null  object
 14  host_thumbnail_url                            18009 non-null  object
 15  host_picture_url                              18009 non-null  object
 16  host_neighbourhood                            4914 non-null   object
 17  host_listings_count                           18017 non-null  int64
 18  host_total_listings_count                     18017 non-null  int64
 19  host_verifications                            18009 non-null  object
 20  host_has_profile_pic                          18009 non-null  object
 21  host_identity_verified                        18009 non-null  object
 22  neighbourhood                                 8410 non-null   object
 23  neighbourhood_cleansed                        18017 non-null  object
 24  neighbourhood_group_cleansed                  0 non-null      float64
 25  latitude                                      18017 non-null  float64
 26  longitude                                     18017 non-null  float64
 27  property_type                                 18017 non-null  object
 28  room_type                                     18017 non-null  object
 29  accommodates                                  18017 non-null  int64
 30  bathrooms                                     17938 non-null  float64
 31  bathrooms_text                                18006 non-null  object
 32  bedrooms                                      18017 non-null  int64
 33  beds                                          18017 non-null  int64
 34  amenities                                     18017 non-null  object
 35  price                                         18017 non-null  float64
 36  minimum_nights                                18017 non-null  int64
 37  maximum_nights                                18017 non-null  int64
 38  minimum_minimum_nights                        18017 non-null  int64
 39  maximum_minimum_nights                        18017 non-null  int64
 40  minimum_maximum_nights                        18017 non-null  int64
 41  maximum_maximum_nights                        18017 non-null  int64
 42  minimum_nights_avg_ntm                        18017 non-null  float64
 43  maximum_nights_avg_ntm                        18017 non-null  float64
 44  calendar_updated                              0 non-null      float64
 45  has_availability                              17869 non-null  object
 46  availability_30                               18017 non-null  int64
 47  availability_60                               18017 non-null  int64
 48  availability_90                               18017 non-null  int64
 49  availability_365                              18017 non-null  int64
 50  calendar_last_scraped                         18017 non-null  datetime64[ns]
 51  number_of_reviews                             18017 non-null  int64
 52  number_of_reviews_ltm                         18017 non-null  int64
 53  number_of_reviews_l30d                        18017 non-null  int64
 54  availability_eoy                              18017 non-null  int64
 55  number_of_reviews_ly                          18017 non-null  int64
 56  estimated_occupancy_l365d                     18017 non-null  int64
 57  estimated_revenue_l365d                       18017 non-null  int64
 58  first_review                                  14983 non-null  datetime64[ns]
 59  last_review                                   14983 non-null  datetime64[ns]
 60  review_scores_rating                          18017 non-null  float64
 61  review_scores_accuracy                        18017 non-null  float64
 62  review_scores_cleanliness                     18017 non-null  float64
 63  review_scores_checkin                         18017 non-null  float64
 64  review_scores_communication                   18017 non-null  float64
 65  review_scores_location                        18017 non-null  float64
 66  review_scores_value                           18017 non-null  float64
 67  license                                       16593 non-null  object
 68  instant_bookable                              18017 non-null  bool
 69  calculated_host_listings_count                18017 non-null  int64
 70  calculated_host_listings_count_entire_homes   18017 non-null  int64
 71  calculated_host_listings_count_private_rooms  18017 non-null  int64
 72  calculated_host_listings_count_shared_rooms   18017 non-null  int64
 73  reviews_per_month                             18017 non-null  float64
dtypes: bool(1), datetime64[ns](4), float64(19), int64(27), object(23)
memory usage: 10.1+ MB

<>:2: SyntaxWarning: invalid escape sequence '\d'
<>:2: SyntaxWarning: invalid escape sequence '\d'
C:\Users\mehul\AppData\Local\Temp\ipykernel_28384\409793288.py:2: SyntaxWarning: invalid escape sequence '\d'
  df['bathrooms'] = df['bathrooms_text'].str.extract('(\d+\.?\d*)').astype(float)

In [65]:
#Drop Old Columns
df.drop(columns=['bathrooms_text'], inplace=True)

In [67]:
#Drop Long Columns
df.drop(columns=['description','neighborhood_overview','host_about'], inplace=True)

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18017 entries, 0 to 18016
Data columns (total 70 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   id                                            18017 non-null  float64
 1   source                                        18017 non-null  object
 2   name                                          18017 non-null  object
 3   host_id                                       18017 non-null  int64
 4   host_name                                     18009 non-null  object
 5   host_since                                    18009 non-null  datetime64[ns]
 6   host_location                                 13300 non-null  object
 7   host_response_time                            15018 non-null  object
 8   host_response_rate                            15018 non-null  float64
 9   host_acceptance_rate                          15812 non-null  float64
 10  host_is_superhost                             17295 non-null  object
 11  host_thumbnail_url                            18009 non-null  object
 12  host_picture_url                              18009 non-null  object
 13  host_neighbourhood                            4914 non-null   object
 14  host_listings_count                           18017 non-null  int64
 15  host_total_listings_count                     18017 non-null  int64
 16  host_verifications                            18009 non-null  object
 17  host_has_profile_pic                          18009 non-null  object
 18  host_identity_verified                        18009 non-null  object
 19  neighbourhood                                 8410 non-null   object
 20  neighbourhood_cleansed                        18017 non-null  object
 21  neighbourhood_group_cleansed                  0 non-null      float64
 22  latitude                                      18017 non-null  float64
 23  longitude                                     18017 non-null  float64
 24  property_type                                 18017 non-null  object
 25  room_type                                     18017 non-null  object
 26  accommodates                                  18017 non-null  int64
 27  bathrooms                                     17938 non-null  float64
 28  bedrooms                                      18017 non-null  int64
 29  beds                                          18017 non-null  int64
 30  amenities                                     18017 non-null  object
 31  price                                         18017 non-null  float64
 32  minimum_nights                                18017 non-null  int64
 33  maximum_nights                                18017 non-null  int64
 34  minimum_minimum_nights                        18017 non-null  int64
 35  maximum_minimum_nights                        18017 non-null  int64
 36  minimum_maximum_nights                        18017 non-null  int64
 37  maximum_maximum_nights                        18017 non-null  int64
 38  minimum_nights_avg_ntm                        18017 non-null  float64
 39  maximum_nights_avg_ntm                        18017 non-null  float64
 40  calendar_updated                              0 non-null      float64
 41  has_availability                              17869 non-null  object
 42  availability_30                               18017 non-null  int64
 43  availability_60                               18017 non-null  int64
 44  availability_90                               18017 non-null  int64
 45  availability_365                              18017 non-null  int64
 46  calendar_last_scraped                         18017 non-null  datetime64[ns]
 47  number_of_reviews                             18017 non-null  int64
 48  number_of_reviews_ltm                         18017 non-null  int64
 49  number_of_reviews_l30d                        18017 non-null  int64
 50  availability_eoy                              18017 non-null  int64
 51  number_of_reviews_ly                          18017 non-null  int64
 52  estimated_occupancy_l365d                     18017 non-null  int64
 53  estimated_revenue_l365d                       18017 non-null  int64
 54  first_review                                  14983 non-null  datetime64[ns]
 55  last_review                                   14983 non-null  datetime64[ns]
 56  review_scores_rating                          18017 non-null  float64
 57  review_scores_accuracy                        18017 non-null  float64
 58  review_scores_cleanliness                     18017 non-null  float64
 59  review_scores_checkin                         18017 non-null  float64
 60  review_scores_communication                   18017 non-null  float64
 61  review_scores_location                        18017 non-null  float64
 62  review_scores_value                           18017 non-null  float64
 63  license                                       16593 non-null  object
 64  instant_bookable                              18017 non-null  bool
 65  calculated_host_listings_count                18017 non-null  int64
 66  calculated_host_listings_count_entire_homes   18017 non-null  int64
 67  calculated_host_listings_count_private_rooms  18017 non-null  int64
 68  calculated_host_listings_count_shared_rooms   18017 non-null  int64
 69  reviews_per_month                             18017 non-null  float64
dtypes: bool(1), datetime64[ns](4), float64(19), int64(27), object(19)
memory usage: 9.5+ MB

In [71]:
#Check Missing Values
df.isnull().sum().sort_values(ascending=False)

neighbourhood_group_cleansed    18017
calendar_updated                18017
host_neighbourhood              13103
neighbourhood                    9607
host_location                    4717
                                ...
minimum_maximum_nights              0
maximum_maximum_nights              0
minimum_nights_avg_ntm              0
maximum_nights_avg_ntm              0
reviews_per_month                   0
Length: 70, dtype: int64

In [73]:
#Drop Column
df.drop(columns=[
'neighbourhood_group_cleansed',
'calendar_updated',
'host_neighbourhood'
], inplace=True)

In [75]:
#Handle Missing Values
df['neighbourhood'].fillna('Unknown', inplace=True)
df['host_location'].fillna('Unknown', inplace=True)

C:\Users\mehul\AppData\Local\Temp\ipykernel_28384\2653276843.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['neighbourhood'].fillna('Unknown', inplace=True)
C:\Users\mehul\AppData\Local\Temp\ipykernel_28384\2653276843.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['host_location'].fillna('Unknown', inplace=True)

In [77]:
#Handle Missing Numeric Values
df['reviews_per_month'].fillna(df['reviews_per_month'].median(), inplace=True)

C:\Users\mehul\AppData\Local\Temp\ipykernel_28384\2764524082.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['reviews_per_month'].fillna(df['reviews_per_month'].median(), inplace=True)

In [79]:
df.isnull().sum().sort_values(ascending=False)

first_review              3034
last_review               3034
host_response_rate        2999
host_response_time        2999
host_acceptance_rate      2205
                          ...
source                       0
minimum_maximum_nights       0
maximum_maximum_nights       0
minimum_nights_avg_ntm       0
reviews_per_month            0
Length: 67, dtype: int64

In [11]:
df['price'].describe()

count     18017
unique     1329
top           0
freq       2473
Name: price, dtype: object

In [15]:
#Clean Price Columns
df['price'] = pd.to_numeric(
    df['price'].astype(str).str.replace('$','').str.replace(',',''),
    errors='coerce'
)
df['price'].describe()

count    18017.000000
mean       320.574013
std        622.353010
min          0.000000
25%        105.000000
50%        206.000000
75%        341.000000
max      29199.000000
Name: price, dtype: float64

In [17]:
df = df[df['price'] > 0]
df['price'].describe()

count    15544.000000
mean       371.576300
std        655.741298
min         16.000000
25%        152.000000
50%        234.000000
75%        373.000000
max      29199.000000
Name: price, dtype: float64

In [23]:
#Remove Outlier(IQR Method)
Q1 = df['price'].quantile(0.25)
Q3 = df['price'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

df = df[(df['price'] >= lower) & (df['price'] <= upper)]
df['price'].describe()

count    13453.000000
mean       228.597190
std        116.444134
min         16.000000
25%        142.000000
50%        210.000000
75%        300.000000
max        545.000000
Name: price, dtype: float64

In [25]:
#Price Per Person
df['price_per_person'] = df['price'] / df['accommodates']

In [31]:
#Host Experiences
df['host_since'] = pd.to_datetime(df['host_since'], errors='coerce')
df['host_since'].dtype  #Verify Datatype

dtype('<M8[ns]')

In [41]:
#Create Host Experience Column
df['host_experience_years'] = 2025 - df['host_since'].dt.year
df['host_experience_years'] = df['host_experience_years'].fillna(0).astype(int) #Change Experience Datatype
df[['host_since','host_experience_years']].head()

  host_since  host_experience_years
1 2013-04-22                     12
2 2013-08-26                     12
4 2009-09-23                     16
5 2009-12-03                     16
6 2010-04-22                     15

In [37]:
#Automatically Update Every Year
df['host_experience_years'] = pd.Timestamp.now().year - df['host_since'].dt.year

In [43]:
#Create Price Column
df['price_category'] = pd.cut(
    df['price'],
    bins=[0,100,250,400,600],
    labels=['Budget','Standard','Premium','Luxury']
)
df[['price','price_category']].head()

   price price_category
1  210.0       Standard
2  157.0       Standard
4   65.0         Budget
5  115.0       Standard
6  185.0       Standard

In [45]:
df['price_category'].value_counts()

price_category
Standard    6577
Premium     3684
Budget      1891
Luxury      1301
Name: count, dtype: int64

In [47]:
#Review Score Category
df['rating_category'] = pd.cut(
    df['review_scores_rating'],
    bins=[0,60,80,90,100],
    labels=['Poor','Average','Good','Excellent']
)

In [57]:

df['first_review'] = pd.to_datetime(df['first_review'], errors='coerce')
df['first_review'].dtype

dtype('<M8[ns]')

In [63]:
#Listing Age
df['listing_age'] = 2025 - df['first_review'].dt.year
df['listing_age'] = df['listing_age'].fillna(0).astype(int) #Change listing Datatype
df['listing_age'] = pd.Timestamp.now().year - df['first_review'].dt.year  #Automatically Update Every year 
df[['first_review','listing_age']].head()

  first_review  listing_age
1   2016-07-24         10.0
2   2015-06-29         11.0
4   2009-12-05         17.0
5   2012-02-23         14.0
6   2010-10-20         16.0

In [65]:
df[['first_review','listing_age']].head()

  first_review  listing_age
1   2016-07-24         10.0
2   2015-06-29         11.0
4   2009-12-05         17.0
5   2012-02-23         14.0
6   2010-10-20         16.0

In [77]:
#Review File Cleaning
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df_reviews =pd.read_csv(r"C:\Users\mehul\OneDrive\Desktop\Data Analyst\AirBNB\Australia\reviews.csv")
df_reviews.head()
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 642151 entries, 0 to 642150
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   listing_id     642151 non-null  int64
 1   id             642151 non-null  int64
 2   date           642151 non-null  object
 3   reviewer_id    642151 non-null  int64
 4   reviewer_name  642151 non-null  object
 5   comments       642060 non-null  object
dtypes: int64(3), object(3)
memory usage: 29.4+ MB

In [83]:
#Check Null Values
df_reviews.isnull().sum()

listing_id       0
id               0
date             0
reviewer_id      0
reviewer_name    0
comments         0
dtype: int64

In [81]:
#Fill Null Value
df_reviews['comments'] = df_reviews['comments'].fillna("No Review")

In [85]:
#Convert Date Column
df_reviews['date'] = pd.to_datetime(df_reviews['date'])
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 642151 entries, 0 to 642150
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   listing_id     642151 non-null  int64
 1   id             642151 non-null  int64
 2   date           642151 non-null  datetime64[ns]
 3   reviewer_id    642151 non-null  int64
 4   reviewer_name  642151 non-null  object
 5   comments       642151 non-null  object
dtypes: datetime64[ns](1), int64(3), object(2)
memory usage: 29.4+ MB

In [97]:
#Calendar File Cleaning
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df_calendar =pd.read_csv(r"C:\Users\mehul\OneDrive\Desktop\Data Analyst\AirBNB\Australia\calendar.csv")
df_calendar.head()

C:\Users\mehul\AppData\Local\Temp\ipykernel_18876\3337747962.py:7: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df_calendar =pd.read_csv(r"C:\Users\mehul\OneDrive\Desktop\Data Analyst\AirBNB\Australia\calendar.csv")

,listing_id,date,available,price,adjusted_price,minimum_nights,maximum_nights
0,11156,03-03-2025,t,$65.00,NaN,90,180
1,11156,04-03-2025,f,$65.00,NaN,90,180
2,11156,05-03-2025,t,$65.00,NaN,90,180
3,11156,06-03-2025,t,$65.00,NaN,90,180
4,11156,07-03-2025,t,$65.00,NaN,90,180

In [3]:
df_calendar.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 7 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   listing_id      1048575 non-null  int64
 1   date            1048575 non-null  object
 2   available       1048575 non-null  object
 3   price           1048575 non-null  object
 4   adjusted_price  1095 non-null     object
 5   minimum_nights  1048575 non-null  int64
 6   maximum_nights  1048575 non-null  int64
dtypes: int64(3), object(4)
memory usage: 56.0+ MB

In [5]:
df_calendar.isnull().sum()

listing_id              0
date                    0
available               0
price                   0
adjusted_price    1047480
minimum_nights          0
maximum_nights          0
dtype: int64

In [7]:
df_calendar.drop(columns=['adjusted_price'], inplace=True)

In [9]:
df_calendar.columns

Index(['listing_id', 'date', 'available', 'price', 'minimum_nights',
       'maximum_nights'],
      dtype='object')

In [15]:
#Convert Date Column
df_calendar['date'] = pd.to_datetime(df_calendar['date'], dayfirst=True)
df_calendar['date'].dtype

dtype('<M8[ns]')

In [17]:
#Clean Price Column
df_calendar['price'] = pd.to_numeric(
    df_calendar['price'].astype(str)
    .str.replace('$','')
    .str.replace(',',''),
    errors='coerce'
)
df_calendar['price'].describe()

count    1.048575e+06
mean     5.167995e+02
std      9.333349e+03
min      2.000000e+01
25%      1.200000e+02
50%      2.000000e+02
75%      3.500000e+02
max      5.000000e+05
Name: price, dtype: float64

In [21]:
#Identify and Remove Outliers 
df_calendar[df_calendar['price'] > 2000].head()
df_calendar = df_calendar[df_calendar['price'] < 2000]
df_calendar['price'].describe()

count    1.029960e+06
mean     2.965081e+02
std      2.907935e+02
min      2.000000e+01
25%      1.200000e+02
50%      1.950000e+02
75%      3.500000e+02
max      1.999000e+03
Name: price, dtype: float64

In [23]:
df_calendar['available'].unique()

array(['t', 'f'], dtype=object)

In [25]:
df_calendar['available'] = df_calendar['available'].map({'t': True, 'f': False})

In [27]:
df_calendar.isnull().sum()

listing_id        0
date              0
available         0
price             0
minimum_nights    0
maximum_nights    0
dtype: int64

In [29]:
#Calculate Listing Metrics
calendar_summary = df_calendar.groupby('listing_id').agg({
    'price':'mean',
    'available':'sum',
    'date':'count'
}).reset_index()

In [31]:
#Rename Column
calendar_summary.columns = [
    'listing_id',
    'avg_price',
    'available_days',
    'total_days'
]

In [33]:
#Calculate Availability Rate
calendar_summary['availability_rate'] = (
    calendar_summary['available_days'] /
    calendar_summary['total_days']
)

In [35]:
#Calculate Booking Rate
calendar_summary['booking_rate'] = 1 - calendar_summary['availability_rate']

In [37]:
calendar_summary.head()

,listing_id,avg_price,available_days,total_days,availability_rate,booking_rate
0,11156,65.0,364,365,0.997260,0.002740
1,15253,99.0,216,365,0.591781,0.408219
2,44545,130.0,5,365,0.013699,0.986301
3,58506,200.0,182,365,0.498630,0.501370
4,68999,115.0,254,365,0.695890,0.304110

In [39]:
#Translate2 File Cleaning
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df_translate2 =pd.read_csv(r"C:\Users\mehul\OneDrive\Desktop\Data Analyst\AirBNB\Australia\translate2.csv")
df_translate2.head()

,listing_id,id,date,reviewer_id,reviewer_name,English
0,1054789,1137290000000000000,17-04-2024,357370888,渡辺,It was nice that it was close to the station.
1,1054789,1143110000000000000,26-04-2024,567632364,Hung,I had a memorable experience.
2,1054789,1160480000000000000,19-05-2024,500074832,창훈,The accommodation is very accessible from the ...
3,1054789,1214870000000000000,03-08-2024,492289313,Nghia,Will comeback again
4,1054789,1244590000000000000,13-09-2024,559549218,Jaehyun,The host is very friendly and respectful

In [43]:
df_translate2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 519533 entries, 0 to 519532
Data columns (total 6 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   listing_id     519533 non-null  int64
 1   id             519533 non-null  int64
 2   date           519533 non-null  object
 3   reviewer_id    519533 non-null  int64
 4   reviewer_name  519533 non-null  object
 5   English        519531 non-null  object
dtypes: int64(3), object(3)
memory usage: 23.8+ MB

In [45]:
df_translate2.shape

(519533, 6)

In [49]:
#Check Missing Value
df_translate2.isnull().sum().sort_values(ascending=False)

English          2
listing_id       0
id               0
date             0
reviewer_id      0
reviewer_name    0
dtype: int64

In [51]:
#Convert Date Column
df_translate2['date'] = pd.to_datetime(df_translate2['date']) 
df_translate2['date'].dtype

C:\Users\mehul\AppData\Local\Temp\ipykernel_18876\3035098097.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_translate2['date'] = pd.to_datetime(df_translate2['date'])

dtype('<M8[ns]')

In [61]:
#Handle Missing English Text
df_translate2[df_translate2['English'].isnull()] 
df_translate2['English'] = df_translate2['English'].fillna('')

In [59]:
df_translate2.columns = df_translate2.columns.str.strip()
df_translate2.columns

Index(['listing_id', 'id', 'date', 'reviewer_id', 'reviewer_name', 'English'], dtype='object')

In [63]:
#Drop Duplicate
df_translate2.duplicated().sum()
df_translate2.drop_duplicates(inplace=True)

In [67]:
#Final Check
df_translate2.isnull().sum()

listing_id       0
id               0
date             0
reviewer_id      0
reviewer_name    0
English          0
dtype: int64

In [71]:
#Load the JSON File
import json

with open(r"C:\Users\mehul\OneDrive\Desktop\Data Analyst\AirBNB\Australia\neighbourhoods.geojson") as f:
    neighbourhood_data = json.load(f)

In [75]:
neighbourhood_data.keys()

dict_keys(['type', 'features'])

In [83]:
#Check File Features
neighbourhood_data['features'][0]

{'type': 'Feature',
 'geometry': {'type': 'MultiPolygon',
  'coordinates': [[[[151.296141, -33.572912],
     [151.296188, -33.572913],
     [151.296234, -33.572912],
     [151.296296, -33.572904],
     [151.296357, -33.57289],
     [151.296418, -33.572872],
     [151.296479, -33.572854],
     [151.296541, -33.572839],
     [151.296618, -33.572828],
     [151.296697, -33.572822],
     [151.296775, -33.572814],
     [151.296849, -33.5728],
     [151.296916, -33.572772],
     [151.296971, -33.572726],
     [151.297017, -33.572666],
     [151.29706, -33.572599],
     [151.297105, -33.572535],
     [151.297158, -33.572483],
     [151.297281, -33.572418],
     [151.297428, -33.572382],
     [151.297588, -33.572365],
     [151.297752, -33.57236],
     [151.297908, -33.57236],
     [151.298129, -33.57237],
     [151.298353, -33.572402],
     [151.298575, -33.572454],
     [151.29879, -33.572524],
     [151.298994, -33.572611],
     [151.299116, -33.572677],
     [151.299234, -33.572752],
     [151.299344, -33.57283],
     [151.299349, -33.572833],
     [151.299462, -33.572917],
     [151.299575, -33.573],
     [151.29966, -33.573068],
     [151.299743, -33.573142],
     [151.299826, -33.573214],
     [151.299912, -33.573278],
     [151.300005, -33.573327],
     [151.300112, -33.57336],
     [151.300226, -33.573378],
     [151.300345, -33.573386],
     [151.300464, -33.573386],
     [151.300581, -33.573384],
     [151.300741, -33.573365],
     [151.3009, -33.573326],
     [151.30106, -33.57328],
     [151.301219, -33.573242],
     [151.301379, -33.573226],
     [151.301547, -33.573234],
     [151.301716, -33.573258],
     [151.301885, -33.573294],
     [151.302052, -33.573339],
     [151.302216, -33.573388],
     [151.302482, -33.573492],
     [151.302738, -33.573626],
     [151.302989, -33.573776],
     [151.30324, -33.57393],
     [151.303494, -33.574073],
     [151.303671, -33.574162],
     [151.303849, -33.574249],
     [151.304027, -33.574336],
     [151.304203, -33.574426],
     [151.304377, -33.574521],
     [151.304509, -33.574593],
     [151.304642, -33.574664],
     [151.304773, -33.574738],
     [151.304896, -33.57482],
     [151.305006, -33.574915],
     [151.305091, -33.575018],
     [151.305163, -33.575134],
     [151.305229, -33.575255],
     [151.305296, -33.575376],
     [151.305372, -33.57549],
     [151.305438, -33.57558],
     [151.305504, -33.575674],
     [151.305574, -33.575763],
     [151.30565, -33.575842],
     [151.305734, -33.575904],
     [151.305833, -33.57595],
     [151.305942, -33.575982],
     [151.306057, -33.576002],
     [151.306173, -33.57601],
     [151.306284, -33.576007],
     [151.306432, -33.575968],
     [151.306576, -33.575891],
     [151.306718, -33.575795],
     [151.306862, -33.575696],
     [151.307009, -33.575614],
     [151.30712, -33.575561],
     [151.307232, -33.575506],
     [151.307345, -33.575456],
     [151.307459, -33.575417],
     [151.307574, -33.575396],
     [151.307713, -33.575399],
     [151.307856, -33.575425],
     [151.308, -33.575469],
     [151.30814, -33.575524],
     [151.308275, -33.575583],
     [151.30845, -33.575667],
     [151.308626, -33.575766],
     [151.308792, -33.575879],
     [151.308933, -33.576008],
     [151.309037, -33.576153],
     [151.309081, -33.576276],
     [151.3091, -33.576411],
     [151.309109, -33.576552],
     [151.309123, -33.576691],
     [151.309158, -33.576822],
     [151.309223, -33.576951],
     [151.309307, -33.577073],
     [151.309399, -33.577191],
     [151.309493, -33.577309],
     [151.309579, -33.57743],
     [151.309671, -33.577582],
     [151.309759, -33.577736],
     [151.309845, -33.577891],
     [151.309932, -33.578046],
     [151.310023, -33.578199],
     [151.310073, -33.578285],
     [151.310123, -33.578373],
     [151.310173, -33.57846],
     [151.310228, -33.578543],
     [151.31029, -33.57862],
     [151.310365, -33.578687],
     [151.31045, -33.578745],
     [151.310538, -33.578801],
     [151.310621, -33.57886],
     [151.310692, -33.57893],
     [151.310757, -33.579021],
     [151.310813, -33.57912],
     [151.31086, -33.579226],
     [151.310896, -33.579335],
     [151.31092, -33.579443],
     [151.318601, -33.57968],
     [151.322533, -33.579801],
     [151.322523, -33.579704],
     [151.322522, -33.579689],
     [151.322522, -33.579661],
     [151.322522, -33.579635],
     [151.322522, -33.579608],
     [151.322523, -33.579581],
     [151.322527, -33.579556],
     [151.322535, -33.579533],
     [151.322548, -33.579513],
     [151.322565, -33.579495],
     [151.322584, -33.579477],
     [151.322605, -33.579461],
     [151.322624, -33.579444],
     [151.322647, -33.579423],
     [151.322669, -33.579402],
     [151.322693, -33.579382],
     [151.322716, -33.579362],
     [151.322739, -33.579342],
     [151.322762, -33.579321],
     [151.322784, -33.5793],
     [151.322807, -33.57928],
     [151.32283, -33.579259],
     [151.322854, -33.57924],
     [151.322887, -33.579216],
     [151.322923, -33.579196],
     [151.322959, -33.579175],
     [151.322992, -33.579152],
     [151.32302, -33.579125],
     [151.323032, -33.579108],
     [151.323043, -33.579091],
     [151.323053, -33.579073],
     [151.323063, -33.579054],
     [151.323071, -33.579035],
     [151.323077, -33.579018],
     [151.323081, -33.578999],
     [151.323085, -33.578981],
     [151.323089, -33.578963],
     [151.323096, -33.578946],
     [151.323111, -33.578922],
     [151.32313, -33.5789],
     [151.323151, -33.578879],
     [151.323175, -33.57886],
     [151.323198, -33.578844],
     [151.323221, -33.578831],
     [151.323245, -33.578821],
     [151.323269, -33.578812],
     [151.323295, -33.578805],
     [151.32332, -33.578799],
     [151.323371, -33.578801],
     [151.323424, -33.578816],
     [151.323479, -33.578837],
     [151.323534, -33.578856],
     [151.323588, -33.578863],
     [151.323639, -33.578858],
     [151.32369, -33.578847],
     [151.323741, -33.578832],
     [151.323792, -33.578815],
     [151.323843, -33.578799],
     [151.323899, -33.578782],
     [151.323955, -33.578762],
     [151.324011, -33.578742],
     [151.324067, -33.578724],
     [151.324124, -33.57871],
     [151.324207, -33.5787],
     [151.324291, -33.578698],
     [151.324376, -33.5787],
     [151.324461, -33.578701],
     [151.324545, -33.578697],
     [151.324612, -33.578689],
     [151.324678, -33.578678],
     [151.324744, -33.578667],
     [151.324811, -33.578655],
     [151.324877, -33.578646],
     [151.324944, -33.578641],
     [151.325078, -33.578637],
     [151.325144, -33.578632],
     [151.325209, -33.578621],
     [151.325269, -33.578602],
     [151.325327, -33.578578],
     [151.325385, -33.578551],
     [151.325443, -33.578525],
     [151.325503, -33.578506],
     [151.32556, -33.578494],
     [151.325619, -33.578486],
     [151.325678, -33.57848],
     [151.325737, -33.578474],
     [151.325796, -33.578468],
     [151.325852, -33.57846],
     [151.325909, -33.578453],
     [151.325965, -33.578446],
     [151.326021, -33.578438],
     [151.326077, -33.578429],
     [151.326116, -33.578424],
     [151.326156, -33.578419],
     [151.326195, -33.578413],
     [151.326233, -33.578404],
     [151.326269, -33.578391],
     [151.326298, -33.578374],
     [151.326325, -33.578351],
     [151.326352, -33.578327],
     [151.326379, -33.578305],
     [151.326409, -33.578289],
     [151.326433, -33.57828],
     [151.326459, -33.578273],
     [151.326485, -33.578267],
     [151.326511, -33.578264],
     [151.326537, -33.578264],
     [151.326567, -33.578269],
     [151.326598, -33.57828],
     [151.326628, -33.578294],
     [151.326659, -33.578307],
     [151.32669, -33.578315],
     [151.326742, -33.578315],
     [151.326795, -33.578306],
     [151.326849, -33.578292],
     [151.326904, -33.578276],
     [151.326958, -33.578264],
     [151.327024, -33.578252],
     [151.32709, -33.578242],
     [151.327157, -33.578232],
     [151.327223, -33.578222],
     [151.32729, -33.578213],
     [151.327355, -33.578203],
     [151.32742, -33.578195],
     [151.327485, -33.578186],
     [151.32755, -33.578177],
     [151.327615, -33.578168],
     [151.3277, -33.578156],
     [151.327784, -33.578143],
     [151.327868, -33.57813],
     [151.327952, -33.578117],
     [151.328037, -33.578104],
     [151.328121, -33.578092],
     [151.328205, -33.578079],
     [151.328289, -33.578066],
     [151.328374, -33.578054],
     [151.328458, -33.57804],
     [151.328519, -33.578029],
     [151.32858, -33.578017],
     [151.328641, -33.578006],
     [151.328703, -33.577996],
     [151.328764, -33.577989],
     [151.328805, -33.577988],
     [151.328846, -33.577987],
     [151.328887, -33.577988],
     [151.328927, -33.577989],
     [151.328968, -33.577989],
     [151.329012, -33.577988],
     [151.329056, -33.577986],
     [151.329099, -33.577985],
     [151.329143, -33.577985],
     [151.329185, -33.577989],
     [151.329217, -33.577994],
     [151.329249, -33.577999],
     [151.329281, -33.578005],
     [151.329311, -33.578015],
     [151.329339, -33.578028],
     [151.329364, -33.578049],
     [151.329386, -33.578076],
     [151.329406, -33.578106],
     [151.329428, -33.578133],
     [151.329453, -33.578155],
     [151.32947, -33.578165],
     [151.329488, -33.578174],
     [151.329506, -33.578182],
     [151.329524, -33.578189],
     [151.329543, -33.578194],
     [151.32956, -33.578196],
     [151.329578, -33.578198],
     [151.329596, -33.578197],
     [151.329614, -33.578196],
     [151.329632, -33.578194],
     [151.329658, -33.578185],
     [151.329683, -33.578171],
     [151.329708, -33.578154],
     [151.329733, -33.57814],
     [151.32976, -33.57813],
     [151.32982, -33.578133],
     [151.329885, -33.578161],
     [151.329953, -33.578202],
     [151.330023, -33.578247],
     [151.330092, -33.578283],
     [151.33013, -33.578298],
     [151.330169, -33.578313],
     [151.330207, -33.578328],
     [151.330246, -33.578343],
     [151.330283, -33.57836],
     [151.330336, -33.578387],
     [151.330387, -33.578416],
     [151.330438, -33.578448],
     [151.330488, -33.57848],
     [151.330538, -33.578513],
     [151.330598, -33.578552],
     [151.330657, -33.578593],
     [151.330716, -33.578634],
     [151.330774, -33.578675],
     [151.330878, -33.57875],
     [151.330924, -33.578783],
     [151.33097, -33.578816],
     [151.331016, -33.57885],
     [151.331062, -33.578883],
     [151.3311, -33.578911],
     [151.331139, -33.578939],
     [151.331177, -33.578967],
     [151.331215, -33.578995],
     [151.331253, -33.579023],
     [151.331289, -33.579051],
     [151.331325, -33.57908],
     [151.33136, -33.579108],
     [151.331396, -33.579136],
     [151.331432, -33.579164],
     [151.331465, -33.579187],
     [151.331498, -33.579211],
     [151.331531, -33.579233],
     [151.331564, -33.579256],
     [151.331598, -33.579279],
     [151.331633, -33.579302],
     [151.331669, -33.579325],
     [151.331705, -33.579347],
     [151.331741, -33.57937],
     [151.331776, -33.579393],
     [151.331813, -33.579418],
     [151.331849, -33.579443],
     [151.331885, -33.579468],
     [151.331921, -33.579494],
     [151.331955, -33.579521],
     [151.33199, -33.57955],
     [151.332025, -33.579579],
     [151.332058, -33.57961],
     [151.332091, -33.579641],
     [151.332121, -33.579674],
     [151.332142, -33.579702],
     [151.332162, -33.57973],
     [151.332181, -33.57976],
     [151.332201, -33.579788],
     [151.332223, -33.579815],
     [151.332254, -33.579843],
     [151.332287, -33.579868],
     [151.332322, -33.579892],
     [151.332356, -33.579916],
     [151.332389, -33.579942],
     [151.332416, -33.579967],
     [151.332441, -33.579992],
     [151.332466, -33.580018],
     [151.332491, -33.580044],
     [151.332517, -33.58007],
     [151.332549, -33.580102],
     [151.332581, -33.580134],
     [151.332614, -33.580165],
     [151.332648, -33.580195],
     [151.332683, -33.580223],
     [151.332726, -33.580255],
     [151.33277, -33.580287],
     [151.332817, -33.580315],
     [151.332864, -33.580338],
     [151.332912, -33.580351],
     [151.332935, -33.580352],
     [151.332958, -33.580351],
     [151.332982, -33.58035],
     [151.333005, -33.580349],
     [151.333027, -33.580351],
     [151.333059, -33.58036],
     [151.333089, -33.580375],
     [151.333119, -33.580392],
     [151.333149, -33.580406],
     [151.333181, -33.580415],
     [151.333206, -33.580417],
     [151.333233, -33.580417],
     [151.33326, -33.580415],
     [151.333285, -33.580411],
     [151.333308, -33.580402],
     [151.333325, -33.580389],
     [151.333339, -33.580372],
     [151.333353, -33.580354],
     [151.333368, -33.580337],
     [151.333385, -33.580325],
     [151.333395, -33.580321],
     [151.333405, -33.580318],
     [151.333415, -33.580315],
     [151.333426, -33.580313],
     [151.333436, -33.580312],
     [151.333455, -33.580315],
     [151.333474, -33.580323],
     [151.333494, -33.580335],
     [151.333511, -33.580349],
     [151.333525, -33.580363],
     [151.333536, -33.580384],
     [151.333542, -33.580409],
     [151.333544, -33.580437],
     [151.333547, -33.580465],
     [151.333551, -33.580491],
     [151.333558, -33.580519],
     [151.333567, -33.580547],
     [151.333576, -33.580575],
     [151.333584, -33.580603],
     [151.333589, -33.580632],
     [151.333593, -33.580662],
     [151.333596, -33.580693],
     [151.333596, -33.580725],
     [151.333595, -33.580755],
     [151.333589, -33.580785],
     [151.333585, -33.580798],
     [151.333579, -33.58081],
     [151.333573, -33.580823],
     [151.333568, -33.580835],
     [151.333563, -33.580848],
     [151.333558, -33.580878],
     [151.333555, -33.580909],
     [151.333556, -33.58094],
     [151.333559, -33.580971],
     [151.333563, -33.581002],
     [151.333571, -33.581036],
     [151.33358, -33.581071],
     [151.333593, -33.581106],
     [151.333609, -33.581138],
     [151.333627, -33.581168],
     [151.33365, -33.581194],
     [151.333677, -33.581219],
     [151.333706, -33.581241],
     [151.333737, -33.581262],
     [151.333768, -33.581282],
     [151.333805, -33.581305],
     [151.333843, -33.581325],
     [151.333883, -33.581343],
     [151.333922, -33.581363],
     [151.333959, -33.581385],
     [151.33399, -33.581408],
     [151.33402, -33.581434],
     [151.334049, -33.58146],
     [151.334079, -33.581483],
     [151.334112, -33.581499],
     [151.334147, -33.581506],
     [151.334184, -33.581506],
     [151.334221, -33.581504],
     [151.334258, -33.581504],
     [151.334291, -33.581512],
     [151.334313, -33.581524],
     [151.334334, -33.581538],
     [151.334354, -33.581554],
     [151.334374, -33.581572],
     [151.334393, -33.581589],
     [151.334412, -33.581606],
     [151.334429, -33.581624],
     [151.334447, -33.581642],
     [151.334464, -33.58166],
     [151.334482, -33.581678],
     [151.334499, -33.581695],
     [151.334516, -33.581712],
     [151.334534, -33.581729],
     [151.334552, -33.581743],
     [151.334572, -33.581755],
     [151.334596, -33.581764],
     [151.334622, -33.58177],
     [151.33465, -33.581774],
     [151.334676, -33.581773],
     [151.334699, -33.581767],
     [151.334705, -33.581765],
     [151.33471, -33.581762],
     [151.334715, -33.581759],
     [151.33472, -33.581757],
     [151.334725, -33.581755],
     [151.334743, -33.581758],
     [151.334765, -33.581775],
     [151.334789, -33.581797],
     [151.334814, -33.581818],
     [151.33484, -33.581831],
     [151.334862, -33.581834],
     [151.334885, -33.581833],
     [151.334909, -33.58183],
     [151.334932, -33.581829],
     [151.334955, -33.581831],
     [151.334985, -33.581846],
     [151.335012, -33.58187],
     [151.335038, -33.581898],
     [151.335065, -33.581925],
     [151.335095, -33.581946],
     [151.335115, -33.581955],
     [151.335137, -33.581961],
     [151.335158, -33.581967],
     [151.335179, -33.581974],
     [151.335194, -33.581983],
     [151.335197, -33.581984],
     [151.335205, -33.581991],
     [151.335213, -33.581999],
     [151.33522, -33.582007],
     [151.335228, -33.582015],
     [151.335235, -33.582023],
     [151.335253, -33.582036],
     [151.335273, -33.582047],
     [151.335293, -33.582059],
     [151.335311, -33.582071],
     [151.335325, -33.582087],
     [151.335332, -33.582101],
     [151.335336, -33.582116],
     [151.33534, -33.582132],
     [151.335344, -33.582148],
     [151.33535, -33.582163],
     [151.335371, -33.582187],
     [151.335399, -33.582206],
     [151.33543, -33.582224],
     [151.335459, -33.582244],
     [151.33548, -33.582267],
     [151.335492, -33.582296],
     [151.335501, -33.582328],
     [151.335505, -33.582362],
     [151.335506, -33.582396],
     [151.335503, -33.582429],
     [151.335498, -33.582453],
     [151.33549, -33.582477],
     [151.33548, -33.5825],
     [151.335469, -33.582522],
     [151.335457, -33.582544],
     [151.335429, -33.582585],
     [151.335395, -33.582624],
     [151.335356, -33.58266],
     [151.335315, -33.582688],
     [151.335272, -33.582706],
     [151.335233, -33.582711],
     [151.335192, -33.582708],
     [151.335149, -33.582701],
     [151.335106, -33.582691],
     [151.335064, -33.582683],
     [151.335013, -33.582671],
     [151.334962, -33.582656],
     [151.334912, -33.582641],
     [151.334861, -33.582626],
     [151.33481, -33.582613],
     [151.334783, -33.582608],
     [151.334755, -33.582602],
     [151.334728, -33.582598],
     [151.3347, -33.582593],
     [151.334672, -33.58259],
     [151.334635, -33.582588],
     [151.334598, -33.582588],
     [151.334561, -33.58259],
     [151.334524, -33.582591],
     [151.334487, -33.58259],
     [151.334437, -33.582587],
     [151.334386, -33.582582],
     [151.334335, -33.582576],
     [151.334284, -33.582571],
     [151.334233, -33.582567],
     [151.334187, -33.582567],
     [151.334141, -33.582569],
     [151.334094, -33.582571],
     [151.334048, -33.582571],
     [151.334003, -33.582567],
     [151.333937, -33.582551],
     [151.333873, -33.582526],
     [151.333809, -33.582497],
     [151.333745, -33.582471],
     [151.33368, -33.582452],
     [151.333638, -33.582444],
     [151.333597, -33.582437],
     [151.333555, -33.582431],
     [151.333513, -33.582428],
     [151.333472, -33.582429],
     [151.333444, -33.582432],
     [151.333417, -33.582437],
     [151.333389, -33.582443],
     [151.333361, -33.582448],
     [151.333333, -33.582452],
     [151.333306, -33.582453],
     [151.333278, -33.582454],
     [151.33325, -33.582453],
     [151.333223, -33.582453],
     [151.333195, -33.582452],
     [151.333149, -33.58245],
     [151.333102, -33.582447],
     [151.333055, -33.582444],
     [151.333009, -33.582438],
     [151.332964, -33.582429],
     [151.332936, -33.58242],
     [151.332909, -33.582411],
     [151.332881, -33.5824],
     [151.332854, -33.58239],
     [151.332826, -33.582382],
     [151.332794, -33.582375],
     [151.332761, -33.582368],
     [151.332729, -33.582362],
     [151.332696, -33.582359],
     [151.332664, -33.582359],
     [151.332632, -33.582364],
     [151.332599, -33.582374],
     [151.332567, -33.582385],
     [151.332535, -33.582397],
     [151.332503, -33.582405],
     [151.332453, -33.582414],
     [151.332402, -33.58242],
     [151.332351, -33.582424],
     [151.3323, -33.582427],
     [151.332249, -33.582428],
     [151.332217, -33.582429],
     [151.332184, -33.582429],
     [151.332152, -33.582429],
     [151.33212, -33.582429],
     [151.332087, -33.582428],
     [151.331829, -33.582428],
     [151.331778, -33.582428],
     [151.331727, -33.582428],
     [151.331626, -33.582428],
     [151.331584, -33.582429],
     [151.331543, -33.58243],
     [151.331501, -33.58243],
     [151.331459, -33.58243],
     [151.331418, -33.582428],
     [151.331381, -33.582425],
     [151.331344, -33.582419],
     [151.331307, -33.582414],
     [151.33127, -33.582409],
     [151.331233, -33.582405],

In [85]:
#Number of Neighbourhood
len(neighbourhood_data['features'])

38

In [107]:
#Merge File
df_final = df.merge(calendar_summary, on='listing_id', how='left')
df_final.shape

(18017, 84)

In [109]:
#Rename Column Name in Listing File
df.rename(columns={'id':'listing_id'}, inplace=True) 
df.columns

Index(['listing_id', 'listing_url', 'scrape_id', 'last_scraped', 'source',
       'name', 'description', 'neighborhood_overview', 'picture_url',
       'host_id', 'host_url', 'host_name', 'host_since', 'host_location',
       'host_about', 'host_response_time', 'host_response_rate',
       'host_acceptance_rate', 'host_is_superhost', 'host_thumbnail_url',
       'host_picture_url', 'host_neighbourhood', 'host_listings_count',
       'host_total_listings_count', 'host_verifications',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'neighbourhood_cleansed', 'neighbourhood_group_cleansed', 'latitude',
       'longitude', 'property_type', 'room_type', 'accommodates', 'bathrooms',
       'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'minimum_minimum_nights',
       'maximum_minimum_nights', 'minimum_maximum_nights',
       'maximum_maximum_nights', 'minimum_nights_avg_ntm',
       'maximum_nights_avg_ntm', 'calendar_updated', 'has_availability',
       'availability_30', 'availability_60', 'availability_90',
       'availability_365', 'calendar_last_scraped', 'number_of_reviews',
       'number_of_reviews_ltm', 'number_of_reviews_l30d', 'availability_eoy',
       'number_of_reviews_ly', 'estimated_occupancy_l365d',
       'estimated_revenue_l365d', 'first_review', 'last_review',
       'review_scores_rating', 'review_scores_accuracy',
       'review_scores_cleanliness', 'review_scores_checkin',
       'review_scores_communication', 'review_scores_location',
       'review_scores_value', 'license', 'instant_bookable',
       'calculated_host_listings_count',
       'calculated_host_listings_count_entire_homes',
       'calculated_host_listings_count_private_rooms',
       'calculated_host_listings_count_shared_rooms', 'reviews_per_month'],
      dtype='object')

In [111]:
df_final.head()

,listing_id,listing_url,scrape_id,last_scraped,source,name,description,neighborhood_overview,picture_url,host_id,...,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,avg_price,available_days,total_days,availability_rate,booking_rate
0,1051911.0,https://www.airbnb.com/rooms/1051911,2.030000e+13,3/3/2025,city scrape,Tree Topz by Beach Stays,Treetopz is a secluded haven perched high abov...,Pittwater on the Northern Beaches of Sydney is...,https://a0.muscache.com/pictures/miso/Hosting-...,24721535,...,73,73,0,0,0.17,620.0,364.0,365.0,0.997260,0.002740
1,1100380.0,https://www.airbnb.com/rooms/1100380,2.030000e+13,3/3/2025,city scrape,"Fabulous location, fabulous place",Fresh and fun Hollywood Regency apartment in t...,The cafes and bars are fantastic. Also some br...,https://a0.muscache.com/pictures/048fc478-6378...,6044810,...,1,1,0,0,0.35,210.0,126.0,365.0,0.345205,0.654795
2,1125557.0,https://www.airbnb.com/rooms/1125557,2.030000e+13,3/3/2025,city scrape,LUXURY BEACHFRONT APARTMENT,"My warm, comfortable two bedroom apartment lie...",I love being so close to nature. Sometimes I s...,https://a0.muscache.com/pictures/77657551/2b77...,8402583,...,1,0,1,0,0.37,190.0,170.0,365.0,0.465753,0.534247
3,1130919.0,https://www.airbnb.com/rooms/1130919,2.030000e+13,3/3/2025,city scrape,Coogee Beach House,Coogee Beach House is contemporary residence i...,In this house you are between Clovelly and Coo...,https://a0.muscache.com/pictures/d7d9da32-d820...,4813247,...,1,1,0,0,0.15,600.0,340.0,365.0,0.931507,0.068493
4,11156.0,https://www.airbnb.com/rooms/11156,2.030000e+13,3/3/2025,city scrape,An Oasis in the City,Very central to the city which can be reached ...,"It is very close to everything and everywhere,...",https://a0.muscache.com/pictures/2797669/17895...,40855,...,1,0,1,0,1.04,65.0,364.0,365.0,0.997260,0.002740

In [113]:
#Merge Review File
review_summary = df_translate2.groupby('listing_id').size().reset_index(name='total_reviews')

In [123]:
df_final = df_final.merge(review_summary, on='listing_id', how='left')
df_final['total_reviews'] = df_final['total_reviews'].fillna(0)

In [121]:
review_summary.head()
review_summary.columns

Index(['listing_id', 'total_reviews'], dtype='object')

In [125]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18017 entries, 0 to 18016
Data columns (total 87 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   listing_id                                    18017 non-null  float64
 1   listing_url                                   18017 non-null  object
 2   scrape_id                                     18017 non-null  float64
 3   last_scraped                                  18017 non-null  object
 4   source                                        18017 non-null  object
 5   name                                          18017 non-null  object
 6   description                                   17703 non-null  object
 7   neighborhood_overview                         8410 non-null   object
 8   picture_url                                   18017 non-null  object
 9   host_id                                       18017 non-null  int64
 10  host_url                                      18017 non-null  object
 11  host_name                                     18009 non-null  object
 12  host_since                                    18009 non-null  object
 13  host_location                                 13300 non-null  object
 14  host_about                                    10480 non-null  object
 15  host_response_time                            15018 non-null  object
 16  host_response_rate                            15018 non-null  object
 17  host_acceptance_rate                          15812 non-null  object
 18  host_is_superhost                             17295 non-null  object
 19  host_thumbnail_url                            18009 non-null  object
 20  host_picture_url                              18009 non-null  object
 21  host_neighbourhood                            4914 non-null   object
 22  host_listings_count                           18017 non-null  int64
 23  host_total_listings_count                     18017 non-null  int64
 24  host_verifications                            18009 non-null  object
 25  host_has_profile_pic                          18009 non-null  object
 26  host_identity_verified                        18009 non-null  object
 27  neighbourhood                                 8410 non-null   object
 28  neighbourhood_cleansed                        18017 non-null  object
 29  neighbourhood_group_cleansed                  0 non-null      float64
 30  latitude                                      18017 non-null  float64
 31  longitude                                     18017 non-null  float64
 32  property_type                                 18017 non-null  object
 33  room_type                                     18017 non-null  object
 34  accommodates                                  18017 non-null  int64
 35  bathrooms                                     18017 non-null  float64
 36  bathrooms_text                                18006 non-null  object
 37  bedrooms                                      18017 non-null  int64
 38  beds                                          18017 non-null  int64
 39  amenities                                     18017 non-null  object
 40  price                                         18017 non-null  object
 41  minimum_nights                                18017 non-null  int64
 42  maximum_nights                                18017 non-null  int64
 43  minimum_minimum_nights                        18017 non-null  int64
 44  maximum_minimum_nights                        18017 non-null  int64
 45  minimum_maximum_nights                        18017 non-null  int64
 46  maximum_maximum_nights                        18017 non-null  int64
 47  minimum_nights_avg_ntm                        18017 non-null  float64
 48  maximum_nights_avg_ntm                        18017 non-null  float64
 49  calendar_updated                              0 non-null      float64
 50  has_availability                              17869 non-null  object
 51  availability_30                               18017 non-null  int64
 52  availability_60                               18017 non-null  int64
 53  availability_90                               18017 non-null  int64
 54  availability_365                              18017 non-null  int64
 55  calendar_last_scraped                         18017 non-null  object
 56  number_of_reviews                             18017 non-null  int64
 57  number_of_reviews_ltm                         18017 non-null  int64
 58  number_of_reviews_l30d                        18017 non-null  int64
 59  availability_eoy                              18017 non-null  int64
 60  number_of_reviews_ly                          18017 non-null  int64
 61  estimated_occupancy_l365d                     18017 non-null  int64
 62  estimated_revenue_l365d                       18017 non-null  int64
 63  first_review                                  14983 non-null  object
 64  last_review                                   14983 non-null  object
 65  review_scores_rating                          18017 non-null  float64
 66  review_scores_accuracy                        18017 non-null  float64
 67  review_scores_cleanliness                     18017 non-null  float64
 68  review_scores_checkin                         18017 non-null  float64
 69  review_scores_communication                   18017 non-null  float64
 70  review_scores_location                        18017 non-null  float64
 71  review_scores_value                           18017 non-null  float64
 72  license                                       16593 non-null  object
 73  instant_bookable                              18017 non-null  object
 74  calculated_host_listings_count                18017 non-null  int64
 75  calculated_host_listings_count_entire_homes   18017 non-null  int64
 76  calculated_host_listings_count_private_rooms  18017 non-null  int64
 77  calculated_host_listings_count_shared_rooms   18017 non-null  int64
 78  reviews_per_month                             18017 non-null  float64
 79  avg_price                                     2822 non-null   float64
 80  available_days                                2822 non-null   float64
 81  total_days                                    2822 non-null   float64
 82  availability_rate                             2822 non-null   float64
 83  booking_rate                                  2822 non-null   float64
 84  total_reviews_x                               17118 non-null  float64
 85  total_reviews_y                               17118 non-null  float64
 86  total_reviews                                 18017 non-null  float64
dtypes: float64(25), int64(27), object(35)
memory usage: 12.0+ MB

In [127]:
#Duplicate Column Remove
df_final[['total_reviews_x','total_reviews_y','total_reviews']].head() 
df_final.drop(columns=['total_reviews_x','total_reviews_y'], inplace=True)

In [129]:
df_final['avg_price'] = df_final['avg_price'].fillna(df_final['price'])
df_final['available_days'] = df_final['available_days'].fillna(0)
df_final['availability_rate'] = df_final['availability_rate'].fillna(0)
df_final['booking_rate'] = df_final['booking_rate'].fillna(0)

In [131]:
df_final['price'] = (
    df_final['price']
    .astype(str)
    .str.replace('$','')
    .str.replace(',','')
    .astype(float)
)

In [133]:
df_final['price'].dtype

dtype('float64')

In [135]:
date_cols = ['first_review','last_review','host_since','last_scraped','calendar_last_scraped']

for col in date_cols:
    df_final[col] = pd.to_datetime(df_final[col], errors='coerce')

In [137]:
#Remove Useless Columns
df_final.drop(columns=['calendar_updated','neighbourhood_group_cleansed'], inplace=True)

In [139]:
#Final Check
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18017 entries, 0 to 18016
Data columns (total 83 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   listing_id                                    18017 non-null  float64
 1   listing_url                                   18017 non-null  object
 2   scrape_id                                     18017 non-null  float64
 3   last_scraped                                  18017 non-null  datetime64[ns]
 4   source                                        18017 non-null  object
 5   name                                          18017 non-null  object
 6   description                                   17703 non-null  object
 7   neighborhood_overview                         8410 non-null   object
 8   picture_url                                   18017 non-null  object
 9   host_id                                       18017 non-null  int64
 10  host_url                                      18017 non-null  object
 11  host_name                                     18009 non-null  object
 12  host_since                                    18009 non-null  datetime64[ns]
 13  host_location                                 13300 non-null  object
 14  host_about                                    10480 non-null  object
 15  host_response_time                            15018 non-null  object
 16  host_response_rate                            15018 non-null  object
 17  host_acceptance_rate                          15812 non-null  object
 18  host_is_superhost                             17295 non-null  object
 19  host_thumbnail_url                            18009 non-null  object
 20  host_picture_url                              18009 non-null  object
 21  host_neighbourhood                            4914 non-null   object
 22  host_listings_count                           18017 non-null  int64
 23  host_total_listings_count                     18017 non-null  int64
 24  host_verifications                            18009 non-null  object
 25  host_has_profile_pic                          18009 non-null  object
 26  host_identity_verified                        18009 non-null  object
 27  neighbourhood                                 8410 non-null   object
 28  neighbourhood_cleansed                        18017 non-null  object
 29  latitude                                      18017 non-null  float64
 30  longitude                                     18017 non-null  float64
 31  property_type                                 18017 non-null  object
 32  room_type                                     18017 non-null  object
 33  accommodates                                  18017 non-null  int64
 34  bathrooms                                     18017 non-null  float64
 35  bathrooms_text                                18006 non-null  object
 36  bedrooms                                      18017 non-null  int64
 37  beds                                          18017 non-null  int64
 38  amenities                                     18017 non-null  object
 39  price                                         18017 non-null  float64
 40  minimum_nights                                18017 non-null  int64
 41  maximum_nights                                18017 non-null  int64
 42  minimum_minimum_nights                        18017 non-null  int64
 43  maximum_minimum_nights                        18017 non-null  int64
 44  minimum_maximum_nights                        18017 non-null  int64
 45  maximum_maximum_nights                        18017 non-null  int64
 46  minimum_nights_avg_ntm                        18017 non-null  float64
 47  maximum_nights_avg_ntm                        18017 non-null  float64
 48  has_availability                              17869 non-null  object
 49  availability_30                               18017 non-null  int64
 50  availability_60                               18017 non-null  int64
 51  availability_90                               18017 non-null  int64
 52  availability_365                              18017 non-null  int64
 53  calendar_last_scraped                         18017 non-null  datetime64[ns]
 54  number_of_reviews                             18017 non-null  int64
 55  number_of_reviews_ltm                         18017 non-null  int64
 56  number_of_reviews_l30d                        18017 non-null  int64
 57  availability_eoy                              18017 non-null  int64
 58  number_of_reviews_ly                          18017 non-null  int64
 59  estimated_occupancy_l365d                     18017 non-null  int64
 60  estimated_revenue_l365d                       18017 non-null  int64
 61  first_review                                  14983 non-null  datetime64[ns]
 62  last_review                                   14983 non-null  datetime64[ns]
 63  review_scores_rating                          18017 non-null  float64
 64  review_scores_accuracy                        18017 non-null  float64
 65  review_scores_cleanliness                     18017 non-null  float64
 66  review_scores_checkin                         18017 non-null  float64
 67  review_scores_communication                   18017 non-null  float64
 68  review_scores_location                        18017 non-null  float64
 69  review_scores_value                           18017 non-null  float64
 70  license                                       16593 non-null  object
 71  instant_bookable                              18017 non-null  object
 72  calculated_host_listings_count                18017 non-null  int64
 73  calculated_host_listings_count_entire_homes   18017 non-null  int64
 74  calculated_host_listings_count_private_rooms  18017 non-null  int64
 75  calculated_host_listings_count_shared_rooms   18017 non-null  int64
 76  reviews_per_month                             18017 non-null  float64
 77  avg_price                                     18017 non-null  object
 78  available_days                                18017 non-null  float64
 79  total_days                                    2822 non-null   float64
 80  availability_rate                             18017 non-null  float64
 81  booking_rate                                  18017 non-null  float64
 82  total_reviews                                 18017 non-null  float64
dtypes: datetime64[ns](5), float64(21), int64(27), object(30)
memory usage: 11.4+ MB

In [141]:
df_final['avg_price'] = pd.to_numeric(df_final['avg_price'], errors='coerce') 
df_final['avg_price'].dtype

dtype('float64')

In [145]:
#Clean Null Values
df_final['total_days'] = df_final['total_days'].fillna(0)
text_cols = ['description','neighborhood_overview','host_about','host_location']

for col in text_cols:
    df_final[col] = df_final[col].fillna('Not Available')

In [147]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18017 entries, 0 to 18016
Data columns (total 83 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   listing_id                                    18017 non-null  float64
 1   listing_url                                   18017 non-null  object
 2   scrape_id                                     18017 non-null  float64
 3   last_scraped                                  18017 non-null  datetime64[ns]
 4   source                                        18017 non-null  object
 5   name                                          18017 non-null  object
 6   description                                   18017 non-null  object
 7   neighborhood_overview                         18017 non-null  object
 8   picture_url                                   18017 non-null  object
 9   host_id                                       18017 non-null  int64
 10  host_url                                      18017 non-null  object
 11  host_name                                     18009 non-null  object
 12  host_since                                    18009 non-null  datetime64[ns]
 13  host_location                                 18017 non-null  object
 14  host_about                                    18017 non-null  object
 15  host_response_time                            15018 non-null  object
 16  host_response_rate                            15018 non-null  object
 17  host_acceptance_rate                          15812 non-null  object
 18  host_is_superhost                             17295 non-null  object
 19  host_thumbnail_url                            18009 non-null  object
 20  host_picture_url                              18009 non-null  object
 21  host_neighbourhood                            4914 non-null   object
 22  host_listings_count                           18017 non-null  int64
 23  host_total_listings_count                     18017 non-null  int64
 24  host_verifications                            18009 non-null  object
 25  host_has_profile_pic                          18009 non-null  object
 26  host_identity_verified                        18009 non-null  object
 27  neighbourhood                                 8410 non-null   object
 28  neighbourhood_cleansed                        18017 non-null  object
 29  latitude                                      18017 non-null  float64
 30  longitude                                     18017 non-null  float64
 31  property_type                                 18017 non-null  object
 32  room_type                                     18017 non-null  object
 33  accommodates                                  18017 non-null  int64
 34  bathrooms                                     18017 non-null  float64
 35  bathrooms_text                                18006 non-null  object
 36  bedrooms                                      18017 non-null  int64
 37  beds                                          18017 non-null  int64
 38  amenities                                     18017 non-null  object
 39  price                                         18017 non-null  float64
 40  minimum_nights                                18017 non-null  int64
 41  maximum_nights                                18017 non-null  int64
 42  minimum_minimum_nights                        18017 non-null  int64
 43  maximum_minimum_nights                        18017 non-null  int64
 44  minimum_maximum_nights                        18017 non-null  int64
 45  maximum_maximum_nights                        18017 non-null  int64
 46  minimum_nights_avg_ntm                        18017 non-null  float64
 47  maximum_nights_avg_ntm                        18017 non-null  float64
 48  has_availability                              17869 non-null  object
 49  availability_30                               18017 non-null  int64
 50  availability_60                               18017 non-null  int64
 51  availability_90                               18017 non-null  int64
 52  availability_365                              18017 non-null  int64
 53  calendar_last_scraped                         18017 non-null  datetime64[ns]
 54  number_of_reviews                             18017 non-null  int64
 55  number_of_reviews_ltm                         18017 non-null  int64
 56  number_of_reviews_l30d                        18017 non-null  int64
 57  availability_eoy                              18017 non-null  int64
 58  number_of_reviews_ly                          18017 non-null  int64
 59  estimated_occupancy_l365d                     18017 non-null  int64
 60  estimated_revenue_l365d                       18017 non-null  int64
 61  first_review                                  14983 non-null  datetime64[ns]
 62  last_review                                   14983 non-null  datetime64[ns]
 63  review_scores_rating                          18017 non-null  float64
 64  review_scores_accuracy                        18017 non-null  float64
 65  review_scores_cleanliness                     18017 non-null  float64
 66  review_scores_checkin                         18017 non-null  float64
 67  review_scores_communication                   18017 non-null  float64
 68  review_scores_location                        18017 non-null  float64
 69  review_scores_value                           18017 non-null  float64
 70  license                                       16593 non-null  object
 71  instant_bookable                              18017 non-null  object
 72  calculated_host_listings_count                18017 non-null  int64
 73  calculated_host_listings_count_entire_homes   18017 non-null  int64
 74  calculated_host_listings_count_private_rooms  18017 non-null  int64
 75  calculated_host_listings_count_shared_rooms   18017 non-null  int64
 76  reviews_per_month                             18017 non-null  float64
 77  avg_price                                     4932 non-null   float64
 78  available_days                                18017 non-null  float64
 79  total_days                                    18017 non-null  float64
 80  availability_rate                             18017 non-null  float64
 81  booking_rate                                  18017 non-null  float64
 82  total_reviews                                 18017 non-null  float64
dtypes: datetime64[ns](5), float64(22), int64(27), object(29)
memory usage: 11.4+ MB

In [149]:
df_final.shape

(18017, 83)

In [151]:
df_final.describe()

,listing_id,scrape_id,last_scraped,host_id,host_since,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,...,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms,calculated_host_listings_count_shared_rooms,reviews_per_month,avg_price,available_days,total_days,availability_rate,booking_rate,total_reviews
count,1.801700e+04,1.801700e+04,18017,1.801700e+04,18009,18017.000000,18017.000000,18017.000000,18017.000000,18017.000000,...,18017.000000,18017.000000,18017.000000,18017.000000,4932.000000,18017.000000,18017.000000,18017.000000,18017.000000,18017.000000
mean,7.119737e+17,2.030000e+13,2025-03-03 00:00:00,2.027744e+08,2017-11-29 00:19:06.626686720,30.720708,45.609702,-33.850777,151.176460,4.061997,...,15.461231,3.951435,0.007937,1.242223,169.659367,29.626686,57.166010,0.081171,0.075459,101.520508
min,1.115600e+04,2.030000e+13,2025-03-03 00:00:00,3.558200e+04,2009-09-02 00:00:00,0.000000,0.000000,-34.132390,150.630490,1.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.223758e+07,2.030000e+13,2025-03-03 00:00:00,2.719164e+07,2015-02-11 00:00:00,1.000000,1.000000,-33.896820,151.135980,2.000000,...,1.000000,0.000000,0.000000,0.140000,0.000000,0.000000,0.000000,0.000000,0.000000,16.000000
50%,9.010000e+17,2.030000e+13,2025-03-03 00:00:00,1.231830e+08,2017-03-29 00:00:00,3.000000,4.000000,-33.874972,151.205450,4.000000,...,1.000000,0.000000,0.000000,0.800000,86.000000,0.000000,0.000000,0.000000,0.000000,58.000000
75%,1.190000e+18,2.030000e+13,2025-03-03 00:00:00,3.426539e+08,2020-03-21 00:00:00,23.000000,33.000000,-33.801870,151.253860,6.000000,...,12.000000,1.000000,0.000000,1.860000,221.250000,0.000000,0.000000,0.000000,0.000000,163.000000
max,1.370000e+18,2.030000e+13,2025-03-03 00:00:00,6.818117e+08,2025-03-01 00:00:00,863.000000,944.000000,-33.383640,151.340140,16.000000,...,189.000000,211.000000,5.000000,17.960000,1999.000000,365.000000,365.000000,1.000000,1.000000,978.000000
std,5.337916e+17,0.000000e+00,NaN,2.019040e+08,NaN,97.022536,122.516210,0.089524,0.114566,2.516219,...,32.971554,23.650871,0.147105,1.446823,264.418513,85.292758,132.655462,0.233679,0.223134,101.045468

In [153]:
df_final.describe(include='object')

,listing_url,source,name,description,neighborhood_overview,picture_url,host_url,host_name,host_location,host_about,...,host_identity_verified,neighbourhood,neighbourhood_cleansed,property_type,room_type,bathrooms_text,amenities,has_availability,license,instant_bookable
count,18017,18017,18017,18017,18017,18017,18017,18009,18017,18017,...,18009,8410,18017,18017,18017,18006,18017,17869,16593,18017
unique,18017,2,17534,16161,6878,17685,9204,3910,727,4387,...,2,1,38,68,4,33,17216,2,11188,2
top,https://www.airbnb.com/rooms/1051911,city scrape,Modern Elegance of Mascot Living,Not Available,Not Available,https://a0.muscache.com/pictures/miso/Hosting-...,https://www.airbnb.com/users/show/288743418,Ken,"Sydney, Australia",Not Available,...,t,Neighborhood highlights,Sydney,Entire rental unit,Entire home/apt,1 bath,"[""Smoke alarm"", ""Fire extinguisher"", ""Shower g...",t,Exempt,f
freq,1,15544,17,314,9607,9,221,249,6255,7537,...,17128,8410,4125,8315,14398,8487,21,17865,3190,12452

In [155]:
#Check Unique Listing
df_final['listing_id'].nunique()

6489

In [157]:
#EDA(Exploratory Data Analysis)-Business Insight
#Listing Dataset
df_listing = df_final.drop_duplicates(subset='listing_id')

In [159]:
df_listing.shape

(6489, 83)

In [161]:
#Room Type Distributions
df_listing['room_type'].value_counts()

room_type
Entire home/apt    4902
Private room       1497
Hotel room           86
Shared room           4
Name: count, dtype: int64

In [163]:
#Average Price
df_listing['price'].describe()

count     6489.000000
mean       312.484358
std        525.876450
min          0.000000
25%        100.000000
50%        197.000000
75%        341.000000
max      12770.000000
Name: price, dtype: float64

In [165]:
#Top Neighborhood
df_listing.groupby('neighbourhood_cleansed')['price'].mean().sort_values(ascending=False).head(10)

neighbourhood_cleansed
Pittwater           655.444196
Woollahra           611.713592
Mosman              512.823009
The Hills Shire     401.361702
Manly               388.710227
Warringah           375.137566
Waverley            367.815748
Sutherland Shire    346.041885
Randwick            312.603865
Fairfield           295.363636
Name: price, dtype: float64